// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: l1/validatorinsurance/v1/query.proto

package validatorinsurancev1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryValidatorInsuranceRequest struct {
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *QueryValidatorInsuranceRequest) Reset()         { *m = QueryValidatorInsuranceRequest{} }
func (m *QueryValidatorInsuranceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorInsuranceRequest) ProtoMessage()    {}
func (*QueryValidatorInsuranceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9abfda7593897fd, []int{0}
}
func (m *QueryValidatorInsuranceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorInsuranceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorInsuranceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorInsuranceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorInsuranceRequest.Merge(m, src)
}
func (m *QueryValidatorInsuranceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorInsuranceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorInsuranceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorInsuranceRequest proto.InternalMessageInfo

func (m *QueryValidatorInsuranceRequest) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

type QueryValidatorInsuranceResponse struct {
	Insurance *ValidatorInsurance `protobuf:"bytes,1,opt,name=insurance,proto3" json:"insurance,omitempty"`
}

func (m *QueryValidatorInsuranceResponse) Reset()         { *m = QueryValidatorInsuranceResponse{} }
func (m *QueryValidatorInsuranceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorInsuranceResponse) ProtoMessage()    {}
func (*QueryValidatorInsuranceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9abfda7593897fd, []int{1}
}
func (m *QueryValidatorInsuranceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorInsuranceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorInsuranceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorInsuranceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorInsuranceResponse.Merge(m, src)
}
func (m *QueryValidatorInsuranceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorInsuranceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorInsuranceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorInsuranceResponse proto.InternalMessageInfo

func (m *QueryValidatorInsuranceResponse) GetInsurance() *ValidatorInsurance {
	if m != nil {
		return m.Insurance
	}
	return nil
}

type QueryInsuranceClaimsRequest struct {
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *QueryInsuranceClaimsRequest) Reset()         { *m = QueryInsuranceClaimsRequest{} }
func (m *QueryInsuranceClaimsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInsuranceClaimsRequest) ProtoMessage()    {}
func (*QueryInsuranceClaimsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9abfda7593897fd, []int{2}
}
func (m *QueryInsuranceClaimsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInsuranceClaimsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInsuranceClaimsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInsuranceClaimsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInsuranceClaimsRequest.Merge(m, src)
}
func (m *QueryInsuranceClaimsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInsuranceClaimsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInsuranceClaimsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInsuranceClaimsRequest proto.InternalMessageInfo

func (m *QueryInsuranceClaimsRequest) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

type QueryInsuranceClaimsResponse struct {
	Claims []InsuranceClaim `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims"`
}

func (m *QueryInsuranceClaimsResponse) Reset()         { *m = QueryInsuranceClaimsResponse{} }
func (m *QueryInsuranceClaimsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInsuranceClaimsResponse) ProtoMessage()    {}
func (*QueryInsuranceClaimsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9abfda7593897fd, []int{3}
}
func (m *QueryInsuranceClaimsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInsuranceClaimsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInsuranceClaimsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInsuranceClaimsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInsuranceClaimsResponse.Merge(m, src)
}
func (m *QueryInsuranceClaimsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInsuranceClaimsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInsuranceClaimsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInsuranceClaimsResponse proto.InternalMessageInfo

func (m *QueryInsuranceClaimsResponse) GetClaims() []InsuranceClaim {
	if m != nil {
		return m.Claims
	}
	return nil
}

type QueryInsuranceParamsRequest struct {
}

func (m *QueryInsuranceParamsRequest) Reset()         { *m = QueryInsuranceParamsRequest{} }
func (m *QueryInsuranceParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInsuranceParamsRequest) ProtoMessage()    {}
func (*QueryInsuranceParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9abfda7593897fd, []int{4}
}
func (m *QueryInsuranceParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInsuranceParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInsuranceParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInsuranceParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInsuranceParamsRequest.Merge(m, src)
}
func (m *QueryInsuranceParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInsuranceParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInsuranceParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInsuranceParamsRequest proto.InternalMessageInfo

type QueryInsuranceParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryInsuranceParamsResponse) Reset()         { *m = QueryInsuranceParamsResponse{} }
func (m *QueryInsuranceParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInsuranceParamsResponse) ProtoMessage()    {}
func (*QueryInsuranceParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9abfda7593897fd, []int{5}
}
func (m *QueryInsuranceParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInsuranceParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInsuranceParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInsuranceParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInsuranceParamsResponse.Merge(m, src)
}
func (m *QueryInsuranceParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInsuranceParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInsuranceParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInsuranceParamsResponse proto.InternalMessageInfo

func (m *QueryInsuranceParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*QueryValidatorInsuranceRequest)(nil), "l1.validatorinsurance.v1.QueryValidatorInsuranceRequest")
	proto.RegisterType((*QueryValidatorInsuranceResponse)(nil), "l1.validatorinsurance.v1.QueryValidatorInsuranceResponse")
	proto.RegisterType((*QueryInsuranceClaimsRequest)(nil), "l1.validatorinsurance.v1.QueryInsuranceClaimsRequest")
	proto.RegisterType((*QueryInsuranceClaimsResponse)(nil), "l1.validatorinsurance.v1.QueryInsuranceClaimsResponse")
	proto.RegisterType((*QueryInsuranceParamsRequest)(nil), "l1.validatorinsurance.v1.QueryInsuranceParamsRequest")
	proto.RegisterType((*QueryInsuranceParamsResponse)(nil), "l1.validatorinsurance.v1.QueryInsuranceParamsResponse")
}

func init() {
	proto.RegisterFile("l1/validatorinsurance/v1/query.proto", fileDescriptor_f9abfda7593897fd)
}

var fileDescriptor_f9abfda7593897fd = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc9, 0x31, 0xd4, 0x2f,
	0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0xc9, 0x2f, 0xca, 0xcc, 0x2b, 0x2e, 0x2d, 0x4a, 0xcc, 0x4b,
	0x4e, 0xd5, 0x2f, 0x33, 0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x92, 0xc8, 0x31, 0xd4, 0xc3, 0x54, 0xa5, 0x57, 0x66, 0x28, 0x25, 0x93, 0x9e, 0x9f, 0x9f,
	0x9e, 0x93, 0xaa, 0x9f, 0x58, 0x90, 0xa9, 0x9f, 0x98, 0x97, 0x97, 0x5f, 0x92, 0x58, 0x92, 0x99,
	0x9f, 0x57, 0x0c, 0xd1, 0x27, 0x25, 0x92, 0x9e, 0x9f, 0x9e, 0x0f, 0x66, 0xea, 0x83, 0x58, 0x50,
	0x51, 0x35, 0x9c, 0x76, 0xa6, 0xa7, 0xe6, 0xa5, 0x16, 0x67, 0x42, 0x75, 0x2b, 0xf9, 0x72, 0xc9,
	0x05, 0x82, 0x1c, 0x11, 0x06, 0x53, 0xeb, 0x09, 0x53, 0x1b, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c,
	0x22, 0xa4, 0xcd, 0x25, 0x08, 0x37, 0x28, 0x3e, 0x31, 0x25, 0xa5, 0x28, 0xb5, 0xb8, 0x58, 0x82,
	0x51, 0x81, 0x51, 0x83, 0x33, 0x48, 0x00, 0x2e, 0xe1, 0x08, 0x11, 0x57, 0xca, 0xe5, 0x92, 0xc7,
	0x69, 0x5c, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x17, 0x17, 0x27, 0xdc, 0x3d, 0x60, 0x73,
	0xb8, 0x8d, 0x74, 0xf4, 0x70, 0xf9, 0x5d, 0x0f, 0x8b, 0x41, 0x08, 0xed, 0x4a, 0x5e, 0x5c, 0xd2,
	0x60, 0xeb, 0xe0, 0x92, 0xce, 0x39, 0x89, 0x99, 0xb9, 0xc5, 0x64, 0x39, 0x3d, 0x8d, 0x4b, 0x06,
	0xbb, 0x59, 0x50, 0x77, 0xbb, 0x71, 0xb1, 0x25, 0x83, 0x45, 0x24, 0x18, 0x15, 0x98, 0x35, 0xb8,
	0x8d, 0x34, 0x70, 0x3b, 0x1a, 0xd5, 0x08, 0x27, 0x96, 0x13, 0xf7, 0xe4, 0x19, 0x82, 0xa0, 0xba,
	0x95, 0x64, 0xd1, 0xdd, 0x1c, 0x90, 0x58, 0x94, 0x08, 0x77, 0xb3, 0x52, 0x1c, 0xba, 0x33, 0x60,
	0xd2, 0x50, 0x67, 0xd8, 0x71, 0xb1, 0x15, 0x80, 0x45, 0xa0, 0x61, 0xa7, 0x80, 0xdb, 0x19, 0x10,
	0x9d, 0x30, 0xeb, 0x21, 0xba, 0x8c, 0x8e, 0xb1, 0x70, 0xb1, 0x82, 0x2d, 0x10, 0x3a, 0xc3, 0xc8,
	0x25, 0x84, 0x19, 0xbc, 0x42, 0x16, 0xb8, 0x0d, 0xc4, 0x9f, 0x52, 0xa4, 0x2c, 0xc9, 0xd0, 0x09,
	0xf1, 0x95, 0x92, 0x63, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0xac, 0x85, 0x2c, 0xf5, 0x91, 0xd3, 0xad,
	0x2e, 0x4a, 0xc2, 0x85, 0x73, 0x8a, 0xf5, 0xab, 0x31, 0xa2, 0xb5, 0x56, 0x68, 0x3f, 0x23, 0x17,
	0x3f, 0x5a, 0xdc, 0x09, 0x99, 0x12, 0x70, 0x11, 0xf6, 0x74, 0x23, 0x65, 0x46, 0xaa, 0x36, 0xa8,
	0x2f, 0x6c, 0xc1, 0xbe, 0x30, 0x17, 0x32, 0xc5, 0xe3, 0x0b, 0x48, 0x2a, 0xc0, 0xea, 0x83, 0xd5,
	0xc8, 0x3e, 0x80, 0x44, 0x1e, 0xf1, 0x3e, 0x40, 0x49, 0x45, 0xc4, 0xfb, 0x00, 0x35, 0x75, 0x29,
	0x69, 0x82, 0x7d, 0xa0, 0x2c, 0xa4, 0x88, 0xc7, 0x07, 0x90, 0x84, 0xe4, 0x94, 0x76, 0xe2, 0x91,
	0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1,
	0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0x3e, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a,
	0xc9, 0xf9, 0xb9, 0xfa, 0xc5, 0xf9, 0x65, 0xa9, 0x45, 0xa9, 0x99, 0xe9, 0x79, 0xba, 0x39, 0x86,
	0x20, 0x33, 0x41, 0x65, 0x18, 0xae, 0xa2, 0xc9, 0x1a, 0x53, 0xb4, 0xcc, 0x30, 0x89, 0x0d, 0x5c,
	0x50, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xf8, 0xd0, 0x6c, 0x46, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	ValidatorInsurance(ctx context.Context, in *QueryValidatorInsuranceRequest, opts ...grpc.CallOption) (*QueryValidatorInsuranceResponse, error)
	InsuranceClaims(ctx context.Context, in *QueryInsuranceClaimsRequest, opts ...grpc.CallOption) (*QueryInsuranceClaimsResponse, error)
	InsuranceParams(ctx context.Context, in *QueryInsuranceParamsRequest, opts ...grpc.CallOption) (*QueryInsuranceParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ValidatorInsurance(ctx context.Context, in *QueryValidatorInsuranceRequest, opts ...grpc.CallOption) (*QueryValidatorInsuranceResponse, error) {
	out := new(QueryValidatorInsuranceResponse)
	err := c.cc.Invoke(ctx, "/l1.validatorinsurance.v1.Query/ValidatorInsurance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InsuranceClaims(ctx context.Context, in *QueryInsuranceClaimsRequest, opts ...grpc.CallOption) (*QueryInsuranceClaimsResponse, error) {
	out := new(QueryInsuranceClaimsResponse)
	err := c.cc.Invoke(ctx, "/l1.validatorinsurance.v1.Query/InsuranceClaims", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InsuranceParams(ctx context.Context, in *QueryInsuranceParamsRequest, opts ...grpc.CallOption) (*QueryInsuranceParamsResponse, error) {
	out := new(QueryInsuranceParamsResponse)
	err := c.cc.Invoke(ctx, "/l1.validatorinsurance.v1.Query/InsuranceParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	ValidatorInsurance(context.Context, *QueryValidatorInsuranceRequest) (*QueryValidatorInsuranceResponse, error)
	InsuranceClaims(context.Context, *QueryInsuranceClaimsRequest) (*QueryInsuranceClaimsResponse, error)
	InsuranceParams(context.Context, *QueryInsuranceParamsRequest) (*QueryInsuranceParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ValidatorInsurance(ctx context.Context, req *QueryValidatorInsuranceRequest) (*QueryValidatorInsuranceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorInsurance not implemented")
}
func (*UnimplementedQueryServer) InsuranceClaims(ctx context.Context, req *QueryInsuranceClaimsRequest) (*QueryInsuranceClaimsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsuranceClaims not implemented")
}
func (*UnimplementedQueryServer) InsuranceParams(ctx context.Context, req *QueryInsuranceParamsRequest) (*QueryInsuranceParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsuranceParams not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ValidatorInsurance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorInsuranceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorInsurance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.validatorinsurance.v1.Query/ValidatorInsurance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorInsurance(ctx, req.(*QueryValidatorInsuranceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InsuranceClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInsuranceClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InsuranceClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.validatorinsurance.v1.Query/InsuranceClaims",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InsuranceClaims(ctx, req.(*QueryInsuranceClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InsuranceParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInsuranceParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InsuranceParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.validatorinsurance.v1.Query/InsuranceParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InsuranceParams(ctx, req.(*QueryInsuranceParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "l1.validatorinsurance.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidatorInsurance",
			Handler:    _Query_ValidatorInsurance_Handler,
		},
		{
			MethodName: "InsuranceClaims",
			Handler:    _Query_InsuranceClaims_Handler,
		},
		{
			MethodName: "InsuranceParams",
			Handler:    _Query_InsuranceParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "l1/validatorinsurance/v1/query.proto",
}

func (m *QueryValidatorInsuranceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorInsuranceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorInsuranceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorInsuranceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorInsuranceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorInsuranceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Insurance != nil {
		{
			size, err := m.Insurance.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInsuranceClaimsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInsuranceClaimsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInsuranceClaimsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInsuranceClaimsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInsuranceClaimsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInsuranceClaimsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Claims) > 0 {
		for iNdEx := len(m.Claims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Claims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryInsuranceParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInsuranceParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInsuranceParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryInsuranceParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInsuranceParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInsuranceParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryValidatorInsuranceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorInsuranceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Insurance != nil {
		l = m.Insurance.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInsuranceClaimsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInsuranceClaimsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Claims) > 0 {
		for _, e := range m.Claims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryInsuranceParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryInsuranceParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryValidatorInsuranceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorInsuranceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorInsuranceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorInsuranceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorInsuranceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorInsuranceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Insurance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Insurance == nil {
				m.Insurance = &ValidatorInsurance{}
			}
			if err := m.Insurance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInsuranceClaimsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInsuranceClaimsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInsuranceClaimsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInsuranceClaimsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInsuranceClaimsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInsuranceClaimsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claims = append(m.Claims, InsuranceClaim{})
			if err := m.Claims[len(m.Claims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInsuranceParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInsuranceParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInsuranceParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInsuranceParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInsuranceParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInsuranceParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
