// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: l1/evidence/v1/tx.proto

package evidencev1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSubmitEvidence struct {
	Authority        string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	EvidenceId       string `protobuf:"bytes,2,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	EvidenceType     string `protobuf:"bytes,3,opt,name=evidence_type,json=evidenceType,proto3" json:"evidence_type,omitempty"`
	AccusedValidator string `protobuf:"bytes,4,opt,name=accused_validator,json=accusedValidator,proto3" json:"accused_validator,omitempty"`
	Reporter         string `protobuf:"bytes,5,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ProofPayloadHash string `protobuf:"bytes,6,opt,name=proof_payload_hash,json=proofPayloadHash,proto3" json:"proof_payload_hash,omitempty"`
	PayloadSizeBytes uint32 `protobuf:"varint,7,opt,name=payload_size_bytes,json=payloadSizeBytes,proto3" json:"payload_size_bytes,omitempty"`
	RequiresReview   bool   `protobuf:"varint,8,opt,name=requires_review,json=requiresReview,proto3" json:"requires_review,omitempty"`
	SlashFractionBps uint32 `protobuf:"varint,9,opt,name=slash_fraction_bps,json=slashFractionBps,proto3" json:"slash_fraction_bps,omitempty"`
	RewardNaet       uint64 `protobuf:"varint,10,opt,name=reward_naet,json=rewardNaet,proto3" json:"reward_naet,omitempty"`
	Height           uint64 `protobuf:"varint,11,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *MsgSubmitEvidence) Reset()         { *m = MsgSubmitEvidence{} }
func (m *MsgSubmitEvidence) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEvidence) ProtoMessage()    {}
func (*MsgSubmitEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2a33fb29fcf4f, []int{0}
}
func (m *MsgSubmitEvidence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitEvidence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEvidence.Merge(m, src)
}
func (m *MsgSubmitEvidence) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEvidence proto.InternalMessageInfo

func (m *MsgSubmitEvidence) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSubmitEvidence) GetEvidenceId() string {
	if m != nil {
		return m.EvidenceId
	}
	return ""
}

func (m *MsgSubmitEvidence) GetEvidenceType() string {
	if m != nil {
		return m.EvidenceType
	}
	return ""
}

func (m *MsgSubmitEvidence) GetAccusedValidator() string {
	if m != nil {
		return m.AccusedValidator
	}
	return ""
}

func (m *MsgSubmitEvidence) GetReporter() string {
	if m != nil {
		return m.Reporter
	}
	return ""
}

func (m *MsgSubmitEvidence) GetProofPayloadHash() string {
	if m != nil {
		return m.ProofPayloadHash
	}
	return ""
}

func (m *MsgSubmitEvidence) GetPayloadSizeBytes() uint32 {
	if m != nil {
		return m.PayloadSizeBytes
	}
	return 0
}

func (m *MsgSubmitEvidence) GetRequiresReview() bool {
	if m != nil {
		return m.RequiresReview
	}
	return false
}

func (m *MsgSubmitEvidence) GetSlashFractionBps() uint32 {
	if m != nil {
		return m.SlashFractionBps
	}
	return 0
}

func (m *MsgSubmitEvidence) GetRewardNaet() uint64 {
	if m != nil {
		return m.RewardNaet
	}
	return 0
}

func (m *MsgSubmitEvidence) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type MsgSubmitEvidenceResponse struct {
	Evidence EvidenceRecord `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence"`
}

func (m *MsgSubmitEvidenceResponse) Reset()         { *m = MsgSubmitEvidenceResponse{} }
func (m *MsgSubmitEvidenceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEvidenceResponse) ProtoMessage()    {}
func (*MsgSubmitEvidenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2a33fb29fcf4f, []int{1}
}
func (m *MsgSubmitEvidenceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitEvidenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitEvidenceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitEvidenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEvidenceResponse.Merge(m, src)
}
func (m *MsgSubmitEvidenceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitEvidenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEvidenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEvidenceResponse proto.InternalMessageInfo

func (m *MsgSubmitEvidenceResponse) GetEvidence() EvidenceRecord {
	if m != nil {
		return m.Evidence
	}
	return EvidenceRecord{}
}

type MsgVoteEvidence struct {
	Authority      string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	EvidenceId     string `protobuf:"bytes,2,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	Voter          string `protobuf:"bytes,3,opt,name=voter,proto3" json:"voter,omitempty"`
	Accept         bool   `protobuf:"varint,4,opt,name=accept,proto3" json:"accept,omitempty"`
	VotingPowerBps uint32 `protobuf:"varint,5,opt,name=voting_power_bps,json=votingPowerBps,proto3" json:"voting_power_bps,omitempty"`
	Height         uint64 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *MsgVoteEvidence) Reset()         { *m = MsgVoteEvidence{} }
func (m *MsgVoteEvidence) String() string { return proto.CompactTextString(m) }
func (*MsgVoteEvidence) ProtoMessage()    {}
func (*MsgVoteEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2a33fb29fcf4f, []int{2}
}
func (m *MsgVoteEvidence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteEvidence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteEvidence.Merge(m, src)
}
func (m *MsgVoteEvidence) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteEvidence proto.InternalMessageInfo

func (m *MsgVoteEvidence) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgVoteEvidence) GetEvidenceId() string {
	if m != nil {
		return m.EvidenceId
	}
	return ""
}

func (m *MsgVoteEvidence) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *MsgVoteEvidence) GetAccept() bool {
	if m != nil {
		return m.Accept
	}
	return false
}

func (m *MsgVoteEvidence) GetVotingPowerBps() uint32 {
	if m != nil {
		return m.VotingPowerBps
	}
	return 0
}

func (m *MsgVoteEvidence) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type MsgVoteEvidenceResponse struct {
	Evidence EvidenceRecord `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence"`
}

func (m *MsgVoteEvidenceResponse) Reset()         { *m = MsgVoteEvidenceResponse{} }
func (m *MsgVoteEvidenceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVoteEvidenceResponse) ProtoMessage()    {}
func (*MsgVoteEvidenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2a33fb29fcf4f, []int{3}
}
func (m *MsgVoteEvidenceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteEvidenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteEvidenceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteEvidenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteEvidenceResponse.Merge(m, src)
}
func (m *MsgVoteEvidenceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteEvidenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteEvidenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteEvidenceResponse proto.InternalMessageInfo

func (m *MsgVoteEvidenceResponse) GetEvidence() EvidenceRecord {
	if m != nil {
		return m.Evidence
	}
	return EvidenceRecord{}
}

type MsgFinalizeEvidence struct {
	Authority  string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	EvidenceId string `protobuf:"bytes,2,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	Height     uint64 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *MsgFinalizeEvidence) Reset()         { *m = MsgFinalizeEvidence{} }
func (m *MsgFinalizeEvidence) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeEvidence) ProtoMessage()    {}
func (*MsgFinalizeEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2a33fb29fcf4f, []int{4}
}
func (m *MsgFinalizeEvidence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinalizeEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinalizeEvidence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinalizeEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeEvidence.Merge(m, src)
}
func (m *MsgFinalizeEvidence) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinalizeEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeEvidence proto.InternalMessageInfo

func (m *MsgFinalizeEvidence) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgFinalizeEvidence) GetEvidenceId() string {
	if m != nil {
		return m.EvidenceId
	}
	return ""
}

func (m *MsgFinalizeEvidence) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type MsgFinalizeEvidenceResponse struct {
	Evidence EvidenceRecord `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence"`
}

func (m *MsgFinalizeEvidenceResponse) Reset()         { *m = MsgFinalizeEvidenceResponse{} }
func (m *MsgFinalizeEvidenceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeEvidenceResponse) ProtoMessage()    {}
func (*MsgFinalizeEvidenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2a33fb29fcf4f, []int{5}
}
func (m *MsgFinalizeEvidenceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinalizeEvidenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinalizeEvidenceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinalizeEvidenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeEvidenceResponse.Merge(m, src)
}
func (m *MsgFinalizeEvidenceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinalizeEvidenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeEvidenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeEvidenceResponse proto.InternalMessageInfo

func (m *MsgFinalizeEvidenceResponse) GetEvidence() EvidenceRecord {
	if m != nil {
		return m.Evidence
	}
	return EvidenceRecord{}
}

type MsgCancelExpiredEvidence struct {
	Authority  string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	EvidenceId string `protobuf:"bytes,2,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	Height     uint64 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *MsgCancelExpiredEvidence) Reset()         { *m = MsgCancelExpiredEvidence{} }
func (m *MsgCancelExpiredEvidence) String() string { return proto.CompactTextString(m) }
func (*MsgCancelExpiredEvidence) ProtoMessage()    {}
func (*MsgCancelExpiredEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2a33fb29fcf4f, []int{6}
}
func (m *MsgCancelExpiredEvidence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelExpiredEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelExpiredEvidence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelExpiredEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelExpiredEvidence.Merge(m, src)
}
func (m *MsgCancelExpiredEvidence) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelExpiredEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelExpiredEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelExpiredEvidence proto.InternalMessageInfo

func (m *MsgCancelExpiredEvidence) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgCancelExpiredEvidence) GetEvidenceId() string {
	if m != nil {
		return m.EvidenceId
	}
	return ""
}

func (m *MsgCancelExpiredEvidence) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type MsgCancelExpiredEvidenceResponse struct {
	Evidence EvidenceRecord `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence"`
}

func (m *MsgCancelExpiredEvidenceResponse) Reset()         { *m = MsgCancelExpiredEvidenceResponse{} }
func (m *MsgCancelExpiredEvidenceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelExpiredEvidenceResponse) ProtoMessage()    {}
func (*MsgCancelExpiredEvidenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2a33fb29fcf4f, []int{7}
}
func (m *MsgCancelExpiredEvidenceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelExpiredEvidenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelExpiredEvidenceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelExpiredEvidenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelExpiredEvidenceResponse.Merge(m, src)
}
func (m *MsgCancelExpiredEvidenceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelExpiredEvidenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelExpiredEvidenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelExpiredEvidenceResponse proto.InternalMessageInfo

func (m *MsgCancelExpiredEvidenceResponse) GetEvidence() EvidenceRecord {
	if m != nil {
		return m.Evidence
	}
	return EvidenceRecord{}
}

func init() {
	proto.RegisterType((*MsgSubmitEvidence)(nil), "l1.evidence.v1.MsgSubmitEvidence")
	proto.RegisterType((*MsgSubmitEvidenceResponse)(nil), "l1.evidence.v1.MsgSubmitEvidenceResponse")
	proto.RegisterType((*MsgVoteEvidence)(nil), "l1.evidence.v1.MsgVoteEvidence")
	proto.RegisterType((*MsgVoteEvidenceResponse)(nil), "l1.evidence.v1.MsgVoteEvidenceResponse")
	proto.RegisterType((*MsgFinalizeEvidence)(nil), "l1.evidence.v1.MsgFinalizeEvidence")
	proto.RegisterType((*MsgFinalizeEvidenceResponse)(nil), "l1.evidence.v1.MsgFinalizeEvidenceResponse")
	proto.RegisterType((*MsgCancelExpiredEvidence)(nil), "l1.evidence.v1.MsgCancelExpiredEvidence")
	proto.RegisterType((*MsgCancelExpiredEvidenceResponse)(nil), "l1.evidence.v1.MsgCancelExpiredEvidenceResponse")
}

func init() { proto.RegisterFile("l1/evidence/v1/tx.proto", fileDescriptor_7ee2a33fb29fcf4f) }

var fileDescriptor_7ee2a33fb29fcf4f = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcf, 0x52, 0xd3, 0x40,
	0x1c, 0x6e, 0x2c, 0xad, 0x65, 0x81, 0x52, 0x22, 0x4a, 0x8c, 0x4c, 0xa9, 0x70, 0xa0, 0x82, 0x36,
	0x16, 0x2f, 0x8e, 0x5e, 0x9c, 0x3a, 0x30, 0x7a, 0xa8, 0xc3, 0x04, 0x87, 0x71, 0x74, 0x34, 0xb3,
	0x4d, 0x7e, 0x24, 0x3b, 0x93, 0x66, 0xe3, 0xee, 0x36, 0x50, 0xc6, 0x83, 0xfa, 0x04, 0xbe, 0x82,
	0x6f, 0xc0, 0x03, 0xf8, 0x00, 0x1c, 0x39, 0x7a, 0x72, 0x1c, 0x38, 0xf0, 0x1a, 0x4e, 0xfe, 0xb5,
	0x52, 0x2a, 0x70, 0xe8, 0x78, 0xdb, 0xfd, 0xbe, 0x6f, 0xbf, 0xcd, 0xef, 0xfb, 0xfd, 0x92, 0xa0,
	0x39, 0xb7, 0xae, 0x41, 0x40, 0x2c, 0xf0, 0x4c, 0xd0, 0x82, 0xba, 0x26, 0xf6, 0x6a, 0x3e, 0xa3,
	0x82, 0xca, 0x45, 0xb7, 0x5e, 0x4b, 0x89, 0x5a, 0x50, 0x57, 0xe7, 0x4c, 0xca, 0xdb, 0x94, 0x6b,
	0x6d, 0x6e, 0x87, 0xba, 0x36, 0xb7, 0x63, 0xa1, 0x3a, 0x6b, 0x53, 0x9b, 0x46, 0x4b, 0x2d, 0x5c,
	0x25, 0xe8, 0xfc, 0x80, 0xaf, 0x0d, 0x1e, 0x70, 0xc2, 0x63, 0x76, 0xf1, 0x47, 0x16, 0xcd, 0x34,
	0xb9, 0xbd, 0xd5, 0x69, 0xb5, 0x89, 0x58, 0x4f, 0x64, 0xf2, 0x3c, 0x1a, 0xc7, 0x1d, 0xe1, 0x50,
	0x46, 0x44, 0x57, 0x91, 0x2a, 0x52, 0x75, 0x5c, 0xef, 0x03, 0xf2, 0x02, 0x9a, 0x48, 0x0d, 0x0d,
	0x62, 0x29, 0xd7, 0x22, 0x1e, 0xa5, 0xd0, 0x4b, 0x4b, 0x5e, 0x42, 0x53, 0x3d, 0x81, 0xe8, 0xfa,
	0xa0, 0x64, 0x23, 0xc9, 0x64, 0x0a, 0xbe, 0xee, 0xfa, 0x20, 0xaf, 0xa2, 0x19, 0x6c, 0x9a, 0x1d,
	0x0e, 0x96, 0x11, 0x60, 0x97, 0x58, 0x58, 0x50, 0xa6, 0x8c, 0x45, 0xc2, 0x52, 0x42, 0x6c, 0xa7,
	0xb8, 0xac, 0xa2, 0x02, 0x03, 0x9f, 0x32, 0x01, 0x4c, 0xc9, 0x45, 0x9a, 0xde, 0x5e, 0xbe, 0x8f,
	0x64, 0x9f, 0x51, 0xba, 0x63, 0xf8, 0xb8, 0xeb, 0x52, 0x6c, 0x19, 0x0e, 0xe6, 0x8e, 0x92, 0x8f,
	0x9d, 0x22, 0x66, 0x33, 0x26, 0x5e, 0x60, 0xee, 0x44, 0xea, 0x44, 0xc7, 0xc9, 0x3e, 0x18, 0xad,
	0xae, 0x00, 0xae, 0x5c, 0xaf, 0x48, 0xd5, 0x29, 0xbd, 0x94, 0x30, 0x5b, 0x64, 0x1f, 0x1a, 0x21,
	0x2e, 0x2f, 0xa3, 0x69, 0x06, 0x1f, 0x3b, 0x84, 0x01, 0x37, 0x18, 0x04, 0x04, 0x76, 0x95, 0x42,
	0x45, 0xaa, 0x16, 0xf4, 0x62, 0x0a, 0xeb, 0x11, 0x1a, 0xda, 0x72, 0x17, 0x73, 0xc7, 0xd8, 0x61,
	0xd8, 0x14, 0x84, 0x7a, 0x46, 0xcb, 0xe7, 0xca, 0x78, 0x6c, 0x1b, 0x31, 0x1b, 0x09, 0xd1, 0xf0,
	0x79, 0x98, 0x20, 0x83, 0x5d, 0xcc, 0x2c, 0xc3, 0xc3, 0x20, 0x14, 0x54, 0x91, 0xaa, 0x63, 0x3a,
	0x8a, 0xa1, 0x57, 0x18, 0x84, 0x7c, 0x0b, 0xe5, 0x1d, 0x20, 0xb6, 0x23, 0x94, 0x89, 0x88, 0x4b,
	0x76, 0x4f, 0x8a, 0x5f, 0x4f, 0x0f, 0x56, 0xfa, 0xad, 0x58, 0x7c, 0x8f, 0x6e, 0x9f, 0xeb, 0x9e,
	0x0e, 0xdc, 0xa7, 0x1e, 0x07, 0xf9, 0x19, 0x2a, 0xa4, 0x89, 0x47, 0x4d, 0x9c, 0x58, 0x2b, 0xd7,
	0xce, 0xce, 0x52, 0xad, 0x7f, 0xc6, 0xa4, 0xcc, 0x6a, 0x8c, 0x1d, 0xfe, 0x5a, 0xc8, 0xe8, 0xbd,
	0x53, 0x8b, 0x47, 0x12, 0x9a, 0x6e, 0x72, 0x7b, 0x9b, 0x0a, 0x18, 0xd5, 0x6c, 0xcc, 0xa2, 0x5c,
	0x40, 0xc3, 0x36, 0xc6, 0x33, 0x11, 0x6f, 0xc2, 0x7a, 0xb1, 0x69, 0x82, 0x2f, 0xa2, 0x09, 0x28,
	0xe8, 0xc9, 0x4e, 0xae, 0xa2, 0x52, 0x40, 0x05, 0xf1, 0x6c, 0xc3, 0xa7, 0xbb, 0xc0, 0xa2, 0x50,
	0x73, 0x51, 0xa8, 0xc5, 0x18, 0xdf, 0x0c, 0xe1, 0x30, 0xd2, 0x7e, 0x62, 0xf9, 0x0b, 0x13, 0x7b,
	0x87, 0xe6, 0x06, 0x2a, 0x1a, 0x61, 0x5e, 0x9f, 0xd0, 0x8d, 0x26, 0xb7, 0x37, 0x88, 0x87, 0x5d,
	0xb2, 0x3f, 0xb2, 0xc8, 0xfa, 0xa5, 0x65, 0x2f, 0x2c, 0xcd, 0x40, 0x77, 0x86, 0xdc, 0x3e, 0xc2,
	0xf2, 0xbe, 0x48, 0x48, 0x69, 0x72, 0xfb, 0x39, 0xf6, 0x4c, 0x70, 0xd7, 0xf7, 0x7c, 0xc2, 0xc0,
	0xfa, 0xdf, 0x45, 0x5a, 0xa8, 0xf2, 0xaf, 0x47, 0x18, 0x5d, 0xa5, 0x6b, 0xdf, 0xb3, 0x28, 0xdb,
	0xe4, 0xb6, 0xfc, 0x01, 0x15, 0x07, 0x3e, 0x8d, 0x77, 0x07, 0x9d, 0xce, 0xbd, 0x7f, 0xea, 0xbd,
	0x4b, 0x25, 0xbd, 0x27, 0x7d, 0x83, 0x26, 0xcf, 0xbc, 0x5c, 0x0b, 0x43, 0x8e, 0xfe, 0x2d, 0x50,
	0x97, 0x2f, 0x11, 0xf4, 0x9c, 0x2d, 0x54, 0x3a, 0x37, 0x87, 0x4b, 0x43, 0x0e, 0x0f, 0x8a, 0xd4,
	0xd5, 0x2b, 0x88, 0x7a, 0xb7, 0x70, 0x74, 0x73, 0xf8, 0x34, 0x54, 0x87, 0xb8, 0x0c, 0x55, 0xaa,
	0x0f, 0xaf, 0xaa, 0x4c, 0x2f, 0x55, 0x73, 0x9f, 0x4f, 0x0f, 0x56, 0xa4, 0x86, 0x7e, 0x78, 0x5c,
	0x96, 0x8e, 0x8e, 0xcb, 0xd2, 0xef, 0xe3, 0xb2, 0xf4, 0xed, 0xa4, 0x9c, 0x39, 0x3a, 0x29, 0x67,
	0x7e, 0x9e, 0x94, 0x33, 0x6f, 0x1f, 0xdb, 0x44, 0x38, 0x9d, 0x56, 0xcd, 0xa4, 0x6d, 0x8d, 0xd3,
	0x00, 0x18, 0x10, 0xdb, 0x7b, 0xe0, 0xd6, 0x35, 0xb7, 0xae, 0x61, 0x9f, 0x68, 0x67, 0xff, 0x88,
	0x4f, 0xd3, 0x75, 0x50, 0x6f, 0xe5, 0xa3, 0xbf, 0xe2, 0xa3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0x16, 0xcc, 0x47, 0x8d, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitEvidence(ctx context.Context, in *MsgSubmitEvidence, opts ...grpc.CallOption) (*MsgSubmitEvidenceResponse, error)
	VoteEvidence(ctx context.Context, in *MsgVoteEvidence, opts ...grpc.CallOption) (*MsgVoteEvidenceResponse, error)
	FinalizeEvidence(ctx context.Context, in *MsgFinalizeEvidence, opts ...grpc.CallOption) (*MsgFinalizeEvidenceResponse, error)
	CancelExpiredEvidence(ctx context.Context, in *MsgCancelExpiredEvidence, opts ...grpc.CallOption) (*MsgCancelExpiredEvidenceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitEvidence(ctx context.Context, in *MsgSubmitEvidence, opts ...grpc.CallOption) (*MsgSubmitEvidenceResponse, error) {
	out := new(MsgSubmitEvidenceResponse)
	err := c.cc.Invoke(ctx, "/l1.evidence.v1.Msg/SubmitEvidence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VoteEvidence(ctx context.Context, in *MsgVoteEvidence, opts ...grpc.CallOption) (*MsgVoteEvidenceResponse, error) {
	out := new(MsgVoteEvidenceResponse)
	err := c.cc.Invoke(ctx, "/l1.evidence.v1.Msg/VoteEvidence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FinalizeEvidence(ctx context.Context, in *MsgFinalizeEvidence, opts ...grpc.CallOption) (*MsgFinalizeEvidenceResponse, error) {
	out := new(MsgFinalizeEvidenceResponse)
	err := c.cc.Invoke(ctx, "/l1.evidence.v1.Msg/FinalizeEvidence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelExpiredEvidence(ctx context.Context, in *MsgCancelExpiredEvidence, opts ...grpc.CallOption) (*MsgCancelExpiredEvidenceResponse, error) {
	out := new(MsgCancelExpiredEvidenceResponse)
	err := c.cc.Invoke(ctx, "/l1.evidence.v1.Msg/CancelExpiredEvidence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitEvidence(context.Context, *MsgSubmitEvidence) (*MsgSubmitEvidenceResponse, error)
	VoteEvidence(context.Context, *MsgVoteEvidence) (*MsgVoteEvidenceResponse, error)
	FinalizeEvidence(context.Context, *MsgFinalizeEvidence) (*MsgFinalizeEvidenceResponse, error)
	CancelExpiredEvidence(context.Context, *MsgCancelExpiredEvidence) (*MsgCancelExpiredEvidenceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitEvidence(ctx context.Context, req *MsgSubmitEvidence) (*MsgSubmitEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEvidence not implemented")
}
func (*UnimplementedMsgServer) VoteEvidence(ctx context.Context, req *MsgVoteEvidence) (*MsgVoteEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteEvidence not implemented")
}
func (*UnimplementedMsgServer) FinalizeEvidence(ctx context.Context, req *MsgFinalizeEvidence) (*MsgFinalizeEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeEvidence not implemented")
}
func (*UnimplementedMsgServer) CancelExpiredEvidence(ctx context.Context, req *MsgCancelExpiredEvidence) (*MsgCancelExpiredEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelExpiredEvidence not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitEvidence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.evidence.v1.Msg/SubmitEvidence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitEvidence(ctx, req.(*MsgSubmitEvidence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VoteEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVoteEvidence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VoteEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.evidence.v1.Msg/VoteEvidence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VoteEvidence(ctx, req.(*MsgVoteEvidence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FinalizeEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFinalizeEvidence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FinalizeEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.evidence.v1.Msg/FinalizeEvidence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FinalizeEvidence(ctx, req.(*MsgFinalizeEvidence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelExpiredEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelExpiredEvidence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelExpiredEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.evidence.v1.Msg/CancelExpiredEvidence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelExpiredEvidence(ctx, req.(*MsgCancelExpiredEvidence))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "l1.evidence.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEvidence",
			Handler:    _Msg_SubmitEvidence_Handler,
		},
		{
			MethodName: "VoteEvidence",
			Handler:    _Msg_VoteEvidence_Handler,
		},
		{
			MethodName: "FinalizeEvidence",
			Handler:    _Msg_FinalizeEvidence_Handler,
		},
		{
			MethodName: "CancelExpiredEvidence",
			Handler:    _Msg_CancelExpiredEvidence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "l1/evidence/v1/tx.proto",
}

func (m *MsgSubmitEvidence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitEvidence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x58
	}
	if m.RewardNaet != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RewardNaet))
		i--
		dAtA[i] = 0x50
	}
	if m.SlashFractionBps != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SlashFractionBps))
		i--
		dAtA[i] = 0x48
	}
	if m.RequiresReview {
		i--
		if m.RequiresReview {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.PayloadSizeBytes != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PayloadSizeBytes))
		i--
		dAtA[i] = 0x38
	}
	if len(m.ProofPayloadHash) > 0 {
		i -= len(m.ProofPayloadHash)
		copy(dAtA[i:], m.ProofPayloadHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ProofPayloadHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Reporter) > 0 {
		i -= len(m.Reporter)
		copy(dAtA[i:], m.Reporter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reporter)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AccusedValidator) > 0 {
		i -= len(m.AccusedValidator)
		copy(dAtA[i:], m.AccusedValidator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AccusedValidator)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.EvidenceType) > 0 {
		i -= len(m.EvidenceType)
		copy(dAtA[i:], m.EvidenceType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvidenceType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EvidenceId) > 0 {
		i -= len(m.EvidenceId)
		copy(dAtA[i:], m.EvidenceId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvidenceId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitEvidenceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitEvidenceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitEvidenceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgVoteEvidence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteEvidence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x30
	}
	if m.VotingPowerBps != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VotingPowerBps))
		i--
		dAtA[i] = 0x28
	}
	if m.Accept {
		i--
		if m.Accept {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EvidenceId) > 0 {
		i -= len(m.EvidenceId)
		copy(dAtA[i:], m.EvidenceId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvidenceId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVoteEvidenceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteEvidenceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteEvidenceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgFinalizeEvidence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinalizeEvidence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinalizeEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x18
	}
	if len(m.EvidenceId) > 0 {
		i -= len(m.EvidenceId)
		copy(dAtA[i:], m.EvidenceId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvidenceId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFinalizeEvidenceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinalizeEvidenceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinalizeEvidenceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgCancelExpiredEvidence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelExpiredEvidence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelExpiredEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x18
	}
	if len(m.EvidenceId) > 0 {
		i -= len(m.EvidenceId)
		copy(dAtA[i:], m.EvidenceId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvidenceId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelExpiredEvidenceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelExpiredEvidenceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelExpiredEvidenceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitEvidence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EvidenceId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EvidenceType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AccusedValidator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Reporter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ProofPayloadHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PayloadSizeBytes != 0 {
		n += 1 + sovTx(uint64(m.PayloadSizeBytes))
	}
	if m.RequiresReview {
		n += 2
	}
	if m.SlashFractionBps != 0 {
		n += 1 + sovTx(uint64(m.SlashFractionBps))
	}
	if m.RewardNaet != 0 {
		n += 1 + sovTx(uint64(m.RewardNaet))
	}
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	return n
}

func (m *MsgSubmitEvidenceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Evidence.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgVoteEvidence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EvidenceId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Accept {
		n += 2
	}
	if m.VotingPowerBps != 0 {
		n += 1 + sovTx(uint64(m.VotingPowerBps))
	}
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	return n
}

func (m *MsgVoteEvidenceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Evidence.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgFinalizeEvidence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EvidenceId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	return n
}

func (m *MsgFinalizeEvidenceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Evidence.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCancelExpiredEvidence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EvidenceId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	return n
}

func (m *MsgCancelExpiredEvidenceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Evidence.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitEvidence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitEvidence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitEvidence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccusedValidator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccusedValidator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reporter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reporter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofPayloadHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProofPayloadHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadSizeBytes", wireType)
			}
			m.PayloadSizeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PayloadSizeBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiresReview", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequiresReview = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionBps", wireType)
			}
			m.SlashFractionBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashFractionBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardNaet", wireType)
			}
			m.RewardNaet = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardNaet |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitEvidenceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitEvidenceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitEvidenceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteEvidence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteEvidence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteEvidence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accept", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Accept = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPowerBps", wireType)
			}
			m.VotingPowerBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingPowerBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteEvidenceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteEvidenceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteEvidenceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFinalizeEvidence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinalizeEvidence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinalizeEvidence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFinalizeEvidenceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinalizeEvidenceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinalizeEvidenceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelExpiredEvidence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelExpiredEvidence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelExpiredEvidence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelExpiredEvidenceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelExpiredEvidenceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelExpiredEvidenceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
