param(
  [string]$Go = "go"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version 2.0

$RepoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.."))

Push-Location $RepoRoot
try {
  & $Go test -p=1 ./x/contracts/types ./x/contracts/keeper -run 'TestContractsKeeperGenesisExportImportInvariantsAndRootContribution|TestContractsKeeperTypedErrorsAndMsgQuerySurface|TestStoreCodeAcceptsRealCompiledBytecodeAndRejectsUndecodableOrForbiddenModules|TestStoreCodeRejectsOversizedAndMalformedBytecodeWithoutMutatingGenesis|TestWalletInstantiatesExecutesAndPassesFunds|TestContractUpgradeMigrationAndAdminPolicy|TestInternalMessagesAndExportImportAreDeterministic|TestAVMContractLifecycleStateMachineEnforced|TestStateInitCounterfactualDeployVirtualQueryAndExternalAttachment'
  & $Go test -p=1 ./x/aetravm/compiler -run 'TestCompileHashCommitmentsChangeOnSchemaAndSelectorMutation|TestCompileFilesPackageImportLock|TestCompileRejectsSelectorCollision'
  & $Go test -p=1 ./x/aetravm/module -run 'TestVerifierCorpusMatchesReferenceModel|TestVerifierMatchesReferenceModel'
  & $Go test -p=1 ./x/aetravm/conformance -run 'TestConformanceDeployInternalBouncedRefundGetter|TestConformanceCanonicalLayoutAndPackageLockStability|TestConformancePurityAndRecursionRulesAreEnforced|TestConformanceSelectorCollisionsAndABIVersionMismatch|TestConformanceGetterOnlyAndScheduledSelfStandardPackages|TestConformanceTreasuryStandardPackageCoversLifecycle|TestConformanceTokenStandardPackageCoversLifecycle|TestConformanceNFTStandardPackageCoversLifecycle|TestConformanceDEXStandardPackageCoversLifecycle|TestConformanceReviewGateMeasuresGasMemoryCodeQueueAndStateGrowth'
  & $Go test -p=1 ./x/aetravm/avm ./x/aetravm/async -run 'TestRunSimpleCounterDeterministicallyAndBoundsGas|TestRunRollsBackStateOnFailure|TestGetterEntryIsReadOnly|TestBouncedContextMismatchIsRejected|TestAVMAsyncFailedSendBouncesAndQueueSurvivesExportImport|TestExportImportPreservesLiveInternalMessageFlow|TestFailedSendProducesDeterministicBounceWithoutDestinationMutation|TestQueueOrderingUsesTxMessageLogicalDestinationAndSequence|TestMessageEnvelopeRequiresGasLimitAndNaetForwardFee|TestBouncedMessageFailureDoesNotCreateBounceLoop|TestExportImportPreservesQueueStateExactly|TestStorageABIExportImportPreservesStorageAndRoot|TestStorageABIStateRootDeterministicForEntryOrder|TestQueueCorpusMatchesReferenceOrder'
  & $Go test -p=1 ./x/aetravm/messageabi -run 'TestEncodeDecodeRoundTripAndDebugJSON'
  & $Go test -p=1 ./cmd/l1d/cmd -run 'TestAVMCLICommandConstruction|TestAVMCLIFeeValidationRejectsMissingOrNonNaetFees|TestAVMCLIE2ESmokeDeployExecuteQuery|TestAVMCLIToolingArtifactsAndSmokeTest|TestAVMLSPInitializeAdvertisesStableCapabilities'
  & $Go test -p=1 ./app -run 'TestAVMRuntimeAppLevelDeployExecuteQueueStorageReceiptsAndExportImport|TestAVMRuntimeAppLevelExecuteInternalRouteAndExportImport|TestAVMRuntimeAppLevelRejectsMaliciousStoreCodeWithoutStateMutation|TestAVMRuntimeAppLevelExportImportPreservesActiveContractsAndBehavior|TestAVMRuntimeAppLevelLifecycleCoversMigrateAndPolicyGuards|TestAVMRuntimeRejectsFrozenAccountsReservedZeroAndRecoversFrozenContracts|TestAVMRuntimeDeterminismGateRejectsNondeterminismAndKeepsStableRoots'
} finally {
  Pop-Location
}

Write-Host "AVM contract standard smoke passed"
