package conformance

import (
	"crypto/ed25519"
	"crypto/sha256"
	"path/filepath"
	"testing"

	secp256k1 "github.com/decred/dcrd/dcrec/secp256k1/v4"
	"github.com/decred/dcrd/dcrec/secp256k1/v4/ecdsa"
	"github.com/hdevalence/ed25519consensus"
	"github.com/stretchr/testify/require"
	"golang.org/x/crypto/sha3"

	"github.com/sovereign-l1/l1/app/addressing"
	"github.com/sovereign-l1/l1/x/aetravm/async"
	"github.com/sovereign-l1/l1/x/aetravm/avm"
	"github.com/sovereign-l1/l1/x/aetravm/compiler"
)

// TestAcceptanceDualSigMultisigExample compiles the cross-scheme 2-of-2 signature
// multisig and asserts (1) it VERIFIES — the compiled module carries the new
// secp256k1 verify / ecrecover opcodes and the ZIP-215 Ed25519 verify and still
// passes interface verification — and (2) each primitive EXECUTES end to end
// through the compiled contract, matching an INDEPENDENT Go computation over the
// same fixed inputs.
//
// The vectors embedded in the .atlx are regenerated here from the same fixed
// private keys and message. Ed25519 is seed-deterministic and the secp256k1
// ECDSA uses RFC6979, so the regenerated bytes are identical to the constants
// the contract verifies; if they were not, the accept getters below would return
// 0 and fail.
func TestAcceptanceDualSigMultisigExample(t *testing.T) {
	deployer := testAddress(0x6a)
	res := compileExampleFile(t, filepath.Join("multisig", "dual_sig_multisig.atlx"), compiler.Options{
		DeployerAddress: addressing.FormatAccAddress(deployer),
	})
	require.NoError(t, avm.VerifyInterface(res.Module, res.Manifest))

	// Rebuild the exact inputs the contract embeds (see dual_sig_multisig.atlx /
	// the vector generator): a fixed 32-byte message, a seeded Ed25519 key, and a
	// fixed secp256k1 private scalar.
	message := make([]byte, 32)
	for i := range message {
		message[i] = byte(0x10 + i)
	}
	digest := sha256.Sum256(message)

	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(0xA0 + i)
	}
	edPriv := ed25519.NewKeyFromSeed(seed)
	edPub := edPriv.Public().(ed25519.PublicKey)
	edSig := ed25519.Sign(edPriv, message)
	require.True(t, ed25519consensus.Verify(edPub, message, edSig), "sanity: ZIP-215 accepts the owner Ed25519 signature")

	privBytes := make([]byte, 32)
	for i := range privBytes {
		privBytes[i] = byte(0x01 + i)
	}
	secpPriv := secp256k1.PrivKeyFromBytes(privBytes)
	secpPub := secpPriv.PubKey()
	// Uncompressed body X‖Y (drop the 0x04 tag) is what ecrecover returns.
	wantRecovered := secpPub.SerializeUncompressed()[1:]

	runner, err := avm.NewRunner(avm.DefaultParams())
	require.NoError(t, err)

	runGetter := func(name string) avm.RuntimeValue {
		op := opcodeForGetter(t, res, name)
		exec, err := runner.Run(res.Module, avm.Storage{}, avm.RuntimeContext{
			Entry:    avm.EntryQuery,
			Message:  async.MessageEnvelope{Opcode: op, GasLimit: 20_000_000},
			GasLimit: 20_000_000,
		})
		require.NoError(t, err)
		require.Equalf(t, async.ResultOK, exec.ResultCode, "getter %q result", name)
		return exec.ReturnValue
	}
	getU64 := func(name string) uint64 {
		u, err := runGetter(name).AsUint64()
		require.NoError(t, err)
		return u
	}
	getBytes := func(name string) []byte {
		b, err := runGetter(name).AsBytes()
		require.NoError(t, err)
		return b
	}

	// Accept path: each scheme, then both together.
	require.Equal(t, uint64(1), getU64("verifyEd25519"), "ZIP-215 Ed25519 must accept the owner signature through the compiled contract")
	require.Equal(t, uint64(1), getU64("verifySecp"), "secp256k1 must accept the owner signature over sha256(message)")
	require.Equal(t, uint64(1), getU64("dualGuard"), "the 2-of-2 guard must pass when BOTH signatures are valid")

	// Canonical low-S: the malleated high-S signature must be rejected.
	require.Equal(t, uint64(0), getU64("verifyHighS"), "a high-S (malleated) secp256k1 signature must be rejected")

	// ecrecover: the recovered 64-byte X‖Y body must equal the signer's key, and
	// independently recovering it in Go must agree.
	gotRecovered := getBytes("recoverSigner")
	require.Len(t, gotRecovered, 64, "ecrecover returns the 64-byte uncompressed X‖Y body")
	require.Equal(t, wantRecovered, gotRecovered, "ecrecover must recover the owner's secp256k1 public key")

	// Cross-check: recover in Go from the same recoverable signature and confirm
	// the on-chain opcode agrees with the library.
	compact := ecdsa.SignCompact(secpPriv, digest[:], false)
	decredCompact := make([]byte, 65)
	decredCompact[0] = compact[0] // 27 + recid, decred layout
	copy(decredCompact[1:], compact[1:])
	recPub, _, err := ecdsa.RecoverCompact(decredCompact, digest[:])
	require.NoError(t, err)
	require.Equal(t, recPub.SerializeUncompressed()[1:], gotRecovered, "Go and AVM ecrecover must agree")

	// End-to-end address derivation: the contract composes ecrecover + keccak256
	// + slice to yield the Ethereum-style address (low 20 bytes of the keccak of
	// the recovered public-key body), which must match the Go computation. This
	// is the exact pipeline a bridge uses to authenticate a foreign signer.
	kh := sha3.NewLegacyKeccak256()
	kh.Write(wantRecovered)
	wantAddr := kh.Sum(nil)[12:]
	require.Equal(t, wantAddr, getBytes("recoveredEthAddress"), "ecrecover→keccak256→slice must derive the right Ethereum address")
}
