// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: l1/reporter/v1/genesis.proto

package reporterv1

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	Authority             string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MinBondAmount         uint64 `protobuf:"varint,2,opt,name=min_bond_amount,json=minBondAmount,proto3" json:"min_bond_amount,omitempty"`
	MaxReporters          uint32 `protobuf:"varint,3,opt,name=max_reporters,json=maxReporters,proto3" json:"max_reporters,omitempty"`
	MaxReports            uint32 `protobuf:"varint,4,opt,name=max_reports,json=maxReports,proto3" json:"max_reports,omitempty"`
	MaxRewardHistory      uint32 `protobuf:"varint,5,opt,name=max_reward_history,json=maxRewardHistory,proto3" json:"max_reward_history,omitempty"`
	MaxReportIdBytes      uint32 `protobuf:"varint,6,opt,name=max_report_id_bytes,json=maxReportIdBytes,proto3" json:"max_report_id_bytes,omitempty"`
	MaxReportTypeBytes    uint32 `protobuf:"varint,7,opt,name=max_report_type_bytes,json=maxReportTypeBytes,proto3" json:"max_report_type_bytes,omitempty"`
	MaxSubjectBytes       uint32 `protobuf:"varint,8,opt,name=max_subject_bytes,json=maxSubjectBytes,proto3" json:"max_subject_bytes,omitempty"`
	MaxPayloadHashBytes   uint32 `protobuf:"varint,9,opt,name=max_payload_hash_bytes,json=maxPayloadHashBytes,proto3" json:"max_payload_hash_bytes,omitempty"`
	MaxPayloadBytes       uint32 `protobuf:"varint,10,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`
	ChallengePeriodBlocks uint64 `protobuf:"varint,11,opt,name=challenge_period_blocks,json=challengePeriodBlocks,proto3" json:"challenge_period_blocks,omitempty"`
	MaliciousSlashBps     uint32 `protobuf:"varint,12,opt,name=malicious_slash_bps,json=maliciousSlashBps,proto3" json:"malicious_slash_bps,omitempty"`
	InitialScore          int64  `protobuf:"varint,13,opt,name=initial_score,json=initialScore,proto3" json:"initial_score,omitempty"`
	AcceptedScoreDelta    int64  `protobuf:"varint,14,opt,name=accepted_score_delta,json=acceptedScoreDelta,proto3" json:"accepted_score_delta,omitempty"`
	RejectedScoreDelta    int64  `protobuf:"varint,15,opt,name=rejected_score_delta,json=rejectedScoreDelta,proto3" json:"rejected_score_delta,omitempty"`
	MaxRewardAmount       uint64 `protobuf:"varint,16,opt,name=max_reward_amount,json=maxRewardAmount,proto3" json:"max_reward_amount,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_961f8ca77fbf10fb, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Params) GetMinBondAmount() uint64 {
	if m != nil {
		return m.MinBondAmount
	}
	return 0
}

func (m *Params) GetMaxReporters() uint32 {
	if m != nil {
		return m.MaxReporters
	}
	return 0
}

func (m *Params) GetMaxReports() uint32 {
	if m != nil {
		return m.MaxReports
	}
	return 0
}

func (m *Params) GetMaxRewardHistory() uint32 {
	if m != nil {
		return m.MaxRewardHistory
	}
	return 0
}

func (m *Params) GetMaxReportIdBytes() uint32 {
	if m != nil {
		return m.MaxReportIdBytes
	}
	return 0
}

func (m *Params) GetMaxReportTypeBytes() uint32 {
	if m != nil {
		return m.MaxReportTypeBytes
	}
	return 0
}

func (m *Params) GetMaxSubjectBytes() uint32 {
	if m != nil {
		return m.MaxSubjectBytes
	}
	return 0
}

func (m *Params) GetMaxPayloadHashBytes() uint32 {
	if m != nil {
		return m.MaxPayloadHashBytes
	}
	return 0
}

func (m *Params) GetMaxPayloadBytes() uint32 {
	if m != nil {
		return m.MaxPayloadBytes
	}
	return 0
}

func (m *Params) GetChallengePeriodBlocks() uint64 {
	if m != nil {
		return m.ChallengePeriodBlocks
	}
	return 0
}

func (m *Params) GetMaliciousSlashBps() uint32 {
	if m != nil {
		return m.MaliciousSlashBps
	}
	return 0
}

func (m *Params) GetInitialScore() int64 {
	if m != nil {
		return m.InitialScore
	}
	return 0
}

func (m *Params) GetAcceptedScoreDelta() int64 {
	if m != nil {
		return m.AcceptedScoreDelta
	}
	return 0
}

func (m *Params) GetRejectedScoreDelta() int64 {
	if m != nil {
		return m.RejectedScoreDelta
	}
	return 0
}

func (m *Params) GetMaxRewardAmount() uint64 {
	if m != nil {
		return m.MaxRewardAmount
	}
	return 0
}

type ReporterReward struct {
	ReportId  string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Amount    uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Claimed   bool   `protobuf:"varint,3,opt,name=claimed,proto3" json:"claimed,omitempty"`
	CreatedAt uint64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClaimedAt uint64 `protobuf:"varint,5,opt,name=claimed_at,json=claimedAt,proto3" json:"claimed_at,omitempty"`
}

func (m *ReporterReward) Reset()         { *m = ReporterReward{} }
func (m *ReporterReward) String() string { return proto.CompactTextString(m) }
func (*ReporterReward) ProtoMessage()    {}
func (*ReporterReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_961f8ca77fbf10fb, []int{1}
}
func (m *ReporterReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReporterReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReporterReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReporterReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReporterReward.Merge(m, src)
}
func (m *ReporterReward) XXX_Size() int {
	return m.Size()
}
func (m *ReporterReward) XXX_DiscardUnknown() {
	xxx_messageInfo_ReporterReward.DiscardUnknown(m)
}

var xxx_messageInfo_ReporterReward proto.InternalMessageInfo

func (m *ReporterReward) GetReportId() string {
	if m != nil {
		return m.ReportId
	}
	return ""
}

func (m *ReporterReward) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReporterReward) GetClaimed() bool {
	if m != nil {
		return m.Claimed
	}
	return false
}

func (m *ReporterReward) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ReporterReward) GetClaimedAt() uint64 {
	if m != nil {
		return m.ClaimedAt
	}
	return 0
}

type ReporterRecord struct {
	ReporterAddress         string           `protobuf:"bytes,1,opt,name=reporter_address,json=reporterAddress,proto3" json:"reporter_address,omitempty"`
	BondedAmount            uint64           `protobuf:"varint,2,opt,name=bonded_amount,json=bondedAmount,proto3" json:"bonded_amount,omitempty"`
	ReporterScore           int64            `protobuf:"varint,3,opt,name=reporter_score,json=reporterScore,proto3" json:"reporter_score,omitempty"`
	AcceptedReports         uint64           `protobuf:"varint,4,opt,name=accepted_reports,json=acceptedReports,proto3" json:"accepted_reports,omitempty"`
	RejectedReports         uint64           `protobuf:"varint,5,opt,name=rejected_reports,json=rejectedReports,proto3" json:"rejected_reports,omitempty"`
	SlashedReporterBond     uint64           `protobuf:"varint,6,opt,name=slashed_reporter_bond,json=slashedReporterBond,proto3" json:"slashed_reporter_bond,omitempty"`
	Status                  string           `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	UnbondingStartHeight    uint64           `protobuf:"varint,8,opt,name=unbonding_start_height,json=unbondingStartHeight,proto3" json:"unbonding_start_height,omitempty"`
	UnbondingCompleteHeight uint64           `protobuf:"varint,9,opt,name=unbonding_complete_height,json=unbondingCompleteHeight,proto3" json:"unbonding_complete_height,omitempty"`
	RewardHistory           []ReporterReward `protobuf:"bytes,10,rep,name=reward_history,json=rewardHistory,proto3" json:"reward_history"`
}

func (m *ReporterRecord) Reset()         { *m = ReporterRecord{} }
func (m *ReporterRecord) String() string { return proto.CompactTextString(m) }
func (*ReporterRecord) ProtoMessage()    {}
func (*ReporterRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_961f8ca77fbf10fb, []int{2}
}
func (m *ReporterRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReporterRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReporterRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReporterRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReporterRecord.Merge(m, src)
}
func (m *ReporterRecord) XXX_Size() int {
	return m.Size()
}
func (m *ReporterRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ReporterRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ReporterRecord proto.InternalMessageInfo

func (m *ReporterRecord) GetReporterAddress() string {
	if m != nil {
		return m.ReporterAddress
	}
	return ""
}

func (m *ReporterRecord) GetBondedAmount() uint64 {
	if m != nil {
		return m.BondedAmount
	}
	return 0
}

func (m *ReporterRecord) GetReporterScore() int64 {
	if m != nil {
		return m.ReporterScore
	}
	return 0
}

func (m *ReporterRecord) GetAcceptedReports() uint64 {
	if m != nil {
		return m.AcceptedReports
	}
	return 0
}

func (m *ReporterRecord) GetRejectedReports() uint64 {
	if m != nil {
		return m.RejectedReports
	}
	return 0
}

func (m *ReporterRecord) GetSlashedReporterBond() uint64 {
	if m != nil {
		return m.SlashedReporterBond
	}
	return 0
}

func (m *ReporterRecord) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ReporterRecord) GetUnbondingStartHeight() uint64 {
	if m != nil {
		return m.UnbondingStartHeight
	}
	return 0
}

func (m *ReporterRecord) GetUnbondingCompleteHeight() uint64 {
	if m != nil {
		return m.UnbondingCompleteHeight
	}
	return 0
}

func (m *ReporterRecord) GetRewardHistory() []ReporterReward {
	if m != nil {
		return m.RewardHistory
	}
	return nil
}

type ReportRecord struct {
	ReportId         string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ReporterAddress  string `protobuf:"bytes,2,opt,name=reporter_address,json=reporterAddress,proto3" json:"reporter_address,omitempty"`
	ReportType       string `protobuf:"bytes,3,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	Subject          string `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	PayloadHash      string `protobuf:"bytes,5,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	PayloadSizeBytes uint32 `protobuf:"varint,6,opt,name=payload_size_bytes,json=payloadSizeBytes,proto3" json:"payload_size_bytes,omitempty"`
	Status           string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	SubmittedHeight  uint64 `protobuf:"varint,8,opt,name=submitted_height,json=submittedHeight,proto3" json:"submitted_height,omitempty"`
	FinalizedHeight  uint64 `protobuf:"varint,9,opt,name=finalized_height,json=finalizedHeight,proto3" json:"finalized_height,omitempty"`
	RewardAmount     uint64 `protobuf:"varint,10,opt,name=reward_amount,json=rewardAmount,proto3" json:"reward_amount,omitempty"`
	RewardClaimed    bool   `protobuf:"varint,11,opt,name=reward_claimed,json=rewardClaimed,proto3" json:"reward_claimed,omitempty"`
	SlashAmount      uint64 `protobuf:"varint,12,opt,name=slash_amount,json=slashAmount,proto3" json:"slash_amount,omitempty"`
}

func (m *ReportRecord) Reset()         { *m = ReportRecord{} }
func (m *ReportRecord) String() string { return proto.CompactTextString(m) }
func (*ReportRecord) ProtoMessage()    {}
func (*ReportRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_961f8ca77fbf10fb, []int{3}
}
func (m *ReportRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReportRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReportRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReportRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRecord.Merge(m, src)
}
func (m *ReportRecord) XXX_Size() int {
	return m.Size()
}
func (m *ReportRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRecord proto.InternalMessageInfo

func (m *ReportRecord) GetReportId() string {
	if m != nil {
		return m.ReportId
	}
	return ""
}

func (m *ReportRecord) GetReporterAddress() string {
	if m != nil {
		return m.ReporterAddress
	}
	return ""
}

func (m *ReportRecord) GetReportType() string {
	if m != nil {
		return m.ReportType
	}
	return ""
}

func (m *ReportRecord) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ReportRecord) GetPayloadHash() string {
	if m != nil {
		return m.PayloadHash
	}
	return ""
}

func (m *ReportRecord) GetPayloadSizeBytes() uint32 {
	if m != nil {
		return m.PayloadSizeBytes
	}
	return 0
}

func (m *ReportRecord) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ReportRecord) GetSubmittedHeight() uint64 {
	if m != nil {
		return m.SubmittedHeight
	}
	return 0
}

func (m *ReportRecord) GetFinalizedHeight() uint64 {
	if m != nil {
		return m.FinalizedHeight
	}
	return 0
}

func (m *ReportRecord) GetRewardAmount() uint64 {
	if m != nil {
		return m.RewardAmount
	}
	return 0
}

func (m *ReportRecord) GetRewardClaimed() bool {
	if m != nil {
		return m.RewardClaimed
	}
	return false
}

func (m *ReportRecord) GetSlashAmount() uint64 {
	if m != nil {
		return m.SlashAmount
	}
	return 0
}

type State struct {
	Reporters []ReporterRecord `protobuf:"bytes,1,rep,name=reporters,proto3" json:"reporters"`
	Reports   []ReportRecord   `protobuf:"bytes,2,rep,name=reports,proto3" json:"reports"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_961f8ca77fbf10fb, []int{4}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_State.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return m.Size()
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetReporters() []ReporterRecord {
	if m != nil {
		return m.Reporters
	}
	return nil
}

func (m *State) GetReports() []ReportRecord {
	if m != nil {
		return m.Reports
	}
	return nil
}

type GenesisState struct {
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Params  Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
	State   State  `protobuf:"bytes,3,opt,name=state,proto3" json:"state"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_961f8ca77fbf10fb, []int{5}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetState() State {
	if m != nil {
		return m.State
	}
	return State{}
}

func init() {
	proto.RegisterType((*Params)(nil), "l1.reporter.v1.Params")
	proto.RegisterType((*ReporterReward)(nil), "l1.reporter.v1.ReporterReward")
	proto.RegisterType((*ReporterRecord)(nil), "l1.reporter.v1.ReporterRecord")
	proto.RegisterType((*ReportRecord)(nil), "l1.reporter.v1.ReportRecord")
	proto.RegisterType((*State)(nil), "l1.reporter.v1.State")
	proto.RegisterType((*GenesisState)(nil), "l1.reporter.v1.GenesisState")
}

func init() { proto.RegisterFile("l1/reporter/v1/genesis.proto", fileDescriptor_961f8ca77fbf10fb) }

var fileDescriptor_961f8ca77fbf10fb = []byte{
	// 1028 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0x4f, 0x6f, 0x23, 0x35,
	0x14, 0xef, 0x34, 0xe9, 0x9f, 0xbc, 0x24, 0x4d, 0xd6, 0xdb, 0x76, 0x07, 0x28, 0x69, 0xb7, 0x2b,
	0x50, 0x8b, 0xd8, 0x84, 0x74, 0x57, 0x08, 0x01, 0x97, 0x66, 0x91, 0x28, 0xe2, 0x52, 0x4d, 0x38,
	0x71, 0x19, 0x39, 0x33, 0x26, 0x31, 0xcc, 0x3f, 0xd9, 0x4e, 0x69, 0xfa, 0x0d, 0xb8, 0xc1, 0x07,
	0xe0, 0xb3, 0x70, 0xdd, 0x13, 0xda, 0x23, 0x27, 0x84, 0xda, 0x0b, 0x1f, 0x03, 0xf9, 0xd9, 0x9e,
	0x64, 0xaa, 0x02, 0xb7, 0xcc, 0xef, 0x8f, 0xed, 0xf8, 0xfd, 0xde, 0x9b, 0x81, 0x83, 0x64, 0x38,
	0x10, 0xac, 0xc8, 0x85, 0x62, 0x62, 0x70, 0x35, 0x1c, 0x4c, 0x59, 0xc6, 0x24, 0x97, 0xfd, 0x42,
	0xe4, 0x2a, 0x27, 0x3b, 0xc9, 0xb0, 0xef, 0xd8, 0xfe, 0xd5, 0xf0, 0xed, 0xdd, 0x69, 0x3e, 0xcd,
	0x91, 0x1a, 0xe8, 0x5f, 0x46, 0x75, 0xfc, 0xfb, 0x06, 0x6c, 0x5e, 0x52, 0x41, 0x53, 0x49, 0x0e,
	0xa0, 0x41, 0xe7, 0x6a, 0x96, 0x0b, 0xae, 0x16, 0xbe, 0x77, 0xe4, 0x9d, 0x34, 0x82, 0x25, 0x40,
	0xde, 0x87, 0x4e, 0xca, 0xb3, 0x70, 0x92, 0x67, 0x71, 0x48, 0xd3, 0x7c, 0x9e, 0x29, 0x7f, 0xfd,
	0xc8, 0x3b, 0xa9, 0x07, 0xed, 0x94, 0x67, 0xa3, 0x3c, 0x8b, 0xcf, 0x11, 0x24, 0xcf, 0xa0, 0x9d,
	0xd2, 0xeb, 0xd0, 0xed, 0x2c, 0xfd, 0xda, 0x91, 0x77, 0xd2, 0x0e, 0x5a, 0x29, 0xbd, 0x0e, 0x1c,
	0x46, 0x0e, 0xa1, 0xb9, 0x14, 0x49, 0xbf, 0x8e, 0x12, 0x28, 0x25, 0x92, 0x7c, 0x08, 0xc4, 0x08,
	0x7e, 0xa4, 0x22, 0x0e, 0x67, 0x5c, 0xaa, 0x5c, 0x2c, 0xfc, 0x0d, 0xd4, 0x75, 0x51, 0xa7, 0x89,
	0x0b, 0x83, 0x93, 0xe7, 0xf0, 0x78, 0xb9, 0x5c, 0xc8, 0xe3, 0x70, 0xb2, 0x50, 0x4c, 0xfa, 0x9b,
	0x2b, 0x72, 0xcd, 0x7c, 0x15, 0x8f, 0x34, 0x4e, 0x86, 0xb0, 0xb7, 0x22, 0x57, 0x8b, 0x82, 0x59,
	0xc3, 0x16, 0x1a, 0x48, 0x69, 0xf8, 0x66, 0x51, 0x30, 0x63, 0xf9, 0x00, 0x1e, 0x69, 0x8b, 0x9c,
	0x4f, 0xbe, 0x67, 0x91, 0xb2, 0xf2, 0x6d, 0x94, 0x77, 0x52, 0x7a, 0x3d, 0x36, 0xb8, 0xd1, 0xbe,
	0x80, 0x7d, 0xad, 0x2d, 0xe8, 0x22, 0xc9, 0x69, 0x1c, 0xce, 0xa8, 0x9c, 0x59, 0x43, 0x03, 0x0d,
	0xfa, 0xac, 0x97, 0x86, 0xbc, 0xa0, 0x72, 0x56, 0xd9, 0xc0, 0x99, 0x8c, 0x1e, 0xca, 0x0d, 0xac,
	0xde, 0x68, 0x3f, 0x86, 0x27, 0xd1, 0x8c, 0x26, 0x09, 0xcb, 0xa6, 0x2c, 0x2c, 0x98, 0xe0, 0x79,
	0x1c, 0x4e, 0x92, 0x3c, 0xfa, 0x41, 0xfa, 0x4d, 0x2c, 0xc9, 0x5e, 0x49, 0x5f, 0x22, 0x3b, 0x42,
	0x92, 0xf4, 0xf5, 0x35, 0x25, 0x3c, 0xe2, 0xf9, 0x5c, 0x86, 0x32, 0xc1, 0x73, 0x15, 0xd2, 0x6f,
	0xe1, 0x2e, 0x8f, 0x4a, 0x6a, 0xac, 0x99, 0x51, 0x21, 0x75, 0x29, 0x79, 0xc6, 0x15, 0xa7, 0x49,
	0x28, 0xa3, 0x5c, 0x30, 0xbf, 0x7d, 0xe4, 0x9d, 0xd4, 0x82, 0x96, 0x05, 0xc7, 0x1a, 0x23, 0x1f,
	0xc1, 0x2e, 0x8d, 0x22, 0x56, 0x28, 0x16, 0x1b, 0x55, 0x18, 0xb3, 0x44, 0x51, 0x7f, 0x07, 0xb5,
	0xc4, 0x71, 0x28, 0xfe, 0x42, 0x33, 0xda, 0x21, 0x98, 0xbe, 0xae, 0x7b, 0x8e, 0x8e, 0x71, 0x38,
	0x6e, 0xc5, 0x61, 0x2f, 0xc7, 0xa6, 0xc1, 0xa6, 0xaf, 0x8b, 0x7f, 0xb5, 0x53, 0x86, 0xc1, 0xe4,
	0xef, 0xf8, 0x57, 0x0f, 0x76, 0x5c, 0xd0, 0x0c, 0x41, 0xde, 0x81, 0x46, 0x19, 0x0d, 0x1b, 0xec,
	0x6d, 0x61, 0x13, 0x41, 0xf6, 0x61, 0xb3, 0x12, 0x67, 0xfb, 0x44, 0x7c, 0xd8, 0x8a, 0x12, 0xca,
	0x53, 0x16, 0x63, 0x82, 0xb7, 0x03, 0xf7, 0x48, 0xde, 0x05, 0x88, 0x04, 0xa3, 0xfa, 0xf8, 0x54,
	0x61, 0x76, 0xeb, 0x41, 0xc3, 0x22, 0xe7, 0x0a, 0x69, 0xa3, 0xd4, 0xf4, 0x86, 0xa5, 0x0d, 0x72,
	0xae, 0x8e, 0xff, 0xae, 0xad, 0x9e, 0x2f, 0xca, 0x45, 0x4c, 0x4e, 0xa1, 0xeb, 0xda, 0x25, 0xa4,
	0x71, 0x2c, 0x98, 0x94, 0xf6, 0x98, 0x1d, 0x87, 0x9f, 0x1b, 0x58, 0x97, 0x44, 0x77, 0x20, 0xbb,
	0xd7, 0x83, 0x2d, 0x03, 0xda, 0x16, 0x7c, 0x0f, 0x76, 0xca, 0xf5, 0x4c, 0xe1, 0x6a, 0x78, 0xb5,
	0x6d, 0x87, 0x9a, 0xca, 0x9d, 0x42, 0xb7, 0xac, 0xdc, 0x6a, 0x27, 0xd6, 0x83, 0x8e, 0xc3, 0x5d,
	0x3b, 0xe2, 0x09, 0x6d, 0xc9, 0x9c, 0xd4, 0xfc, 0xb3, 0x8e, 0xc3, 0x9d, 0xf4, 0x0c, 0xf6, 0x30,
	0x5a, 0xa5, 0x92, 0x09, 0x1c, 0x1a, 0xd8, 0x8d, 0xf5, 0xe0, 0xb1, 0x25, 0xdd, 0x15, 0xe8, 0xc9,
	0xa1, 0x6b, 0x20, 0x15, 0x55, 0x73, 0xd3, 0x81, 0x8d, 0xc0, 0x3e, 0x91, 0x97, 0xb0, 0x3f, 0xcf,
	0xb4, 0x99, 0x67, 0xd3, 0x50, 0x2a, 0x2a, 0x54, 0x38, 0x63, 0x7c, 0x3a, 0x53, 0xd8, 0x7a, 0xf5,
	0x60, 0xb7, 0x64, 0xc7, 0x9a, 0xbc, 0x40, 0x8e, 0x7c, 0x0a, 0x6f, 0x2d, 0x5d, 0x51, 0x9e, 0x16,
	0x09, 0x53, 0xcc, 0x19, 0x1b, 0x68, 0x7c, 0x52, 0x0a, 0x5e, 0x59, 0xde, 0x7a, 0xbf, 0xd6, 0x57,
	0x57, 0x99, 0x39, 0x70, 0x54, 0x3b, 0x69, 0x9e, 0xf5, 0xfa, 0xd5, 0x69, 0xda, 0xaf, 0x46, 0x6c,
	0x54, 0x7f, 0xfd, 0xe7, 0xe1, 0x9a, 0xbe, 0xe0, 0x95, 0xb1, 0x74, 0xfc, 0x5b, 0x0d, 0x5a, 0x46,
	0x67, 0x0b, 0xfd, 0x9f, 0x41, 0x7c, 0x28, 0x05, 0xeb, 0x0f, 0xa7, 0xe0, 0x10, 0x9a, 0x2b, 0xc3,
	0x0b, 0xab, 0xdb, 0x08, 0x40, 0x94, 0x33, 0x4b, 0x87, 0xd7, 0x8e, 0x2a, 0xac, 0x68, 0x23, 0x70,
	0x8f, 0xe4, 0x29, 0xb4, 0x56, 0x07, 0x13, 0x56, 0xb1, 0x11, 0x34, 0x8b, 0xe5, 0x3c, 0xd2, 0xb3,
	0xd7, 0x49, 0x24, 0xbf, 0x61, 0xd5, 0x61, 0x6a, 0x99, 0x31, 0xbf, 0xb1, 0x93, 0xf1, 0xdf, 0x6a,
	0x77, 0x0a, 0x5d, 0x39, 0x9f, 0xa4, 0x5c, 0xe9, 0xcc, 0x54, 0xaa, 0xd6, 0x29, 0x71, 0x7b, 0xe9,
	0xa7, 0xd0, 0xfd, 0x8e, 0x67, 0x34, 0xe1, 0x37, 0x4b, 0xa9, 0xa9, 0x53, 0xa7, 0xc4, 0xad, 0xf4,
	0x19, 0xb4, 0xab, 0x53, 0x00, 0x4c, 0xfe, 0xc5, 0xca, 0x08, 0x30, 0xf9, 0x47, 0x91, 0xeb, 0xe0,
	0x26, 0x76, 0xb0, 0xb5, 0xbe, 0xb2, 0x7d, 0xfc, 0x14, 0x5a, 0x66, 0x08, 0xda, 0xa5, 0x5a, 0xb8,
	0x54, 0x13, 0x31, 0x3b, 0x4c, 0x7e, 0xf2, 0x60, 0x63, 0xac, 0xa8, 0x62, 0x64, 0xe4, 0x4a, 0xa7,
	0x5f, 0x69, 0xde, 0xff, 0x65, 0x42, 0x57, 0xdb, 0x66, 0x62, 0x69, 0x23, 0x9f, 0xc3, 0x96, 0x6b,
	0x9e, 0x75, 0x5c, 0xe1, 0xe0, 0xe1, 0x15, 0x2a, 0x7e, 0x67, 0x39, 0xfe, 0xc5, 0x83, 0xd6, 0x97,
	0xe6, 0x0d, 0x6f, 0x8e, 0xe4, 0xc3, 0xd6, 0x15, 0x13, 0x92, 0xe7, 0x19, 0x66, 0xa9, 0x1e, 0xb8,
	0x47, 0xf2, 0x12, 0x36, 0x0b, 0x7c, 0xa7, 0x63, 0x80, 0x9a, 0x67, 0xfb, 0xf7, 0xf7, 0x31, 0x6f,
	0x7c, 0xbb, 0x83, 0xd5, 0x92, 0x21, 0x6c, 0xe8, 0xda, 0x99, 0x3c, 0x35, 0xcf, 0xf6, 0xee, 0x9b,
	0x70, 0x57, 0xeb, 0x31, 0xca, 0x51, 0xf0, 0xfa, 0xb6, 0xe7, 0xbd, 0xb9, 0xed, 0x79, 0x7f, 0xdd,
	0xf6, 0xbc, 0x9f, 0xef, 0x7a, 0x6b, 0x6f, 0xee, 0x7a, 0x6b, 0x7f, 0xdc, 0xf5, 0xd6, 0xbe, 0xfd,
	0x64, 0xca, 0xd5, 0x6c, 0x3e, 0xe9, 0x47, 0x79, 0x3a, 0x90, 0xf9, 0x15, 0x13, 0x8c, 0x4f, 0xb3,
	0xe7, 0xc9, 0x70, 0x90, 0x0c, 0x07, 0xb4, 0xe0, 0x83, 0xea, 0xa7, 0xcb, 0x67, 0xee, 0xf7, 0xd5,
	0x70, 0xb2, 0x89, 0x1f, 0x26, 0x2f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x64, 0xe7, 0xc6, 0x88,
	0xde, 0x08, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxRewardAmount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxRewardAmount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.RejectedScoreDelta != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RejectedScoreDelta))
		i--
		dAtA[i] = 0x78
	}
	if m.AcceptedScoreDelta != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AcceptedScoreDelta))
		i--
		dAtA[i] = 0x70
	}
	if m.InitialScore != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.InitialScore))
		i--
		dAtA[i] = 0x68
	}
	if m.MaliciousSlashBps != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaliciousSlashBps))
		i--
		dAtA[i] = 0x60
	}
	if m.ChallengePeriodBlocks != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ChallengePeriodBlocks))
		i--
		dAtA[i] = 0x58
	}
	if m.MaxPayloadBytes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxPayloadBytes))
		i--
		dAtA[i] = 0x50
	}
	if m.MaxPayloadHashBytes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxPayloadHashBytes))
		i--
		dAtA[i] = 0x48
	}
	if m.MaxSubjectBytes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxSubjectBytes))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxReportTypeBytes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxReportTypeBytes))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxReportIdBytes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxReportIdBytes))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxRewardHistory != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxRewardHistory))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxReports != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxReports))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxReporters != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxReporters))
		i--
		dAtA[i] = 0x18
	}
	if m.MinBondAmount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MinBondAmount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReporterReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReporterReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReporterReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClaimedAt != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ClaimedAt))
		i--
		dAtA[i] = 0x28
	}
	if m.CreatedAt != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	if m.Claimed {
		i--
		if m.Claimed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Amount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ReportId) > 0 {
		i -= len(m.ReportId)
		copy(dAtA[i:], m.ReportId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ReportId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReporterRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReporterRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReporterRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RewardHistory) > 0 {
		for iNdEx := len(m.RewardHistory) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardHistory[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.UnbondingCompleteHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UnbondingCompleteHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.UnbondingStartHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UnbondingStartHeight))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	if m.SlashedReporterBond != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SlashedReporterBond))
		i--
		dAtA[i] = 0x30
	}
	if m.RejectedReports != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RejectedReports))
		i--
		dAtA[i] = 0x28
	}
	if m.AcceptedReports != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AcceptedReports))
		i--
		dAtA[i] = 0x20
	}
	if m.ReporterScore != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ReporterScore))
		i--
		dAtA[i] = 0x18
	}
	if m.BondedAmount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BondedAmount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ReporterAddress) > 0 {
		i -= len(m.ReporterAddress)
		copy(dAtA[i:], m.ReporterAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ReporterAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReportRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReportRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReportRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SlashAmount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SlashAmount))
		i--
		dAtA[i] = 0x60
	}
	if m.RewardClaimed {
		i--
		if m.RewardClaimed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.RewardAmount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RewardAmount))
		i--
		dAtA[i] = 0x50
	}
	if m.FinalizedHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.FinalizedHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.SubmittedHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SubmittedHeight))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	if m.PayloadSizeBytes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PayloadSizeBytes))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PayloadHash) > 0 {
		i -= len(m.PayloadHash)
		copy(dAtA[i:], m.PayloadHash)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PayloadHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Subject) > 0 {
		i -= len(m.Subject)
		copy(dAtA[i:], m.Subject)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Subject)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ReportType) > 0 {
		i -= len(m.ReportType)
		copy(dAtA[i:], m.ReportType)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ReportType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ReporterAddress) > 0 {
		i -= len(m.ReporterAddress)
		copy(dAtA[i:], m.ReporterAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ReporterAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ReportId) > 0 {
		i -= len(m.ReportId)
		copy(dAtA[i:], m.ReportId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ReportId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *State) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *State) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *State) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reports) > 0 {
		for iNdEx := len(m.Reports) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reports[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Reporters) > 0 {
		for iNdEx := len(m.Reporters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reporters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Version != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.MinBondAmount != 0 {
		n += 1 + sovGenesis(uint64(m.MinBondAmount))
	}
	if m.MaxReporters != 0 {
		n += 1 + sovGenesis(uint64(m.MaxReporters))
	}
	if m.MaxReports != 0 {
		n += 1 + sovGenesis(uint64(m.MaxReports))
	}
	if m.MaxRewardHistory != 0 {
		n += 1 + sovGenesis(uint64(m.MaxRewardHistory))
	}
	if m.MaxReportIdBytes != 0 {
		n += 1 + sovGenesis(uint64(m.MaxReportIdBytes))
	}
	if m.MaxReportTypeBytes != 0 {
		n += 1 + sovGenesis(uint64(m.MaxReportTypeBytes))
	}
	if m.MaxSubjectBytes != 0 {
		n += 1 + sovGenesis(uint64(m.MaxSubjectBytes))
	}
	if m.MaxPayloadHashBytes != 0 {
		n += 1 + sovGenesis(uint64(m.MaxPayloadHashBytes))
	}
	if m.MaxPayloadBytes != 0 {
		n += 1 + sovGenesis(uint64(m.MaxPayloadBytes))
	}
	if m.ChallengePeriodBlocks != 0 {
		n += 1 + sovGenesis(uint64(m.ChallengePeriodBlocks))
	}
	if m.MaliciousSlashBps != 0 {
		n += 1 + sovGenesis(uint64(m.MaliciousSlashBps))
	}
	if m.InitialScore != 0 {
		n += 1 + sovGenesis(uint64(m.InitialScore))
	}
	if m.AcceptedScoreDelta != 0 {
		n += 1 + sovGenesis(uint64(m.AcceptedScoreDelta))
	}
	if m.RejectedScoreDelta != 0 {
		n += 1 + sovGenesis(uint64(m.RejectedScoreDelta))
	}
	if m.MaxRewardAmount != 0 {
		n += 2 + sovGenesis(uint64(m.MaxRewardAmount))
	}
	return n
}

func (m *ReporterReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReportId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovGenesis(uint64(m.Amount))
	}
	if m.Claimed {
		n += 2
	}
	if m.CreatedAt != 0 {
		n += 1 + sovGenesis(uint64(m.CreatedAt))
	}
	if m.ClaimedAt != 0 {
		n += 1 + sovGenesis(uint64(m.ClaimedAt))
	}
	return n
}

func (m *ReporterRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReporterAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.BondedAmount != 0 {
		n += 1 + sovGenesis(uint64(m.BondedAmount))
	}
	if m.ReporterScore != 0 {
		n += 1 + sovGenesis(uint64(m.ReporterScore))
	}
	if m.AcceptedReports != 0 {
		n += 1 + sovGenesis(uint64(m.AcceptedReports))
	}
	if m.RejectedReports != 0 {
		n += 1 + sovGenesis(uint64(m.RejectedReports))
	}
	if m.SlashedReporterBond != 0 {
		n += 1 + sovGenesis(uint64(m.SlashedReporterBond))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.UnbondingStartHeight != 0 {
		n += 1 + sovGenesis(uint64(m.UnbondingStartHeight))
	}
	if m.UnbondingCompleteHeight != 0 {
		n += 1 + sovGenesis(uint64(m.UnbondingCompleteHeight))
	}
	if len(m.RewardHistory) > 0 {
		for _, e := range m.RewardHistory {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *ReportRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReportId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ReporterAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ReportType)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.PayloadHash)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.PayloadSizeBytes != 0 {
		n += 1 + sovGenesis(uint64(m.PayloadSizeBytes))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.SubmittedHeight != 0 {
		n += 1 + sovGenesis(uint64(m.SubmittedHeight))
	}
	if m.FinalizedHeight != 0 {
		n += 1 + sovGenesis(uint64(m.FinalizedHeight))
	}
	if m.RewardAmount != 0 {
		n += 1 + sovGenesis(uint64(m.RewardAmount))
	}
	if m.RewardClaimed {
		n += 2
	}
	if m.SlashAmount != 0 {
		n += 1 + sovGenesis(uint64(m.SlashAmount))
	}
	return n
}

func (m *State) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Reporters) > 0 {
		for _, e := range m.Reporters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Reports) > 0 {
		for _, e := range m.Reports {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovGenesis(uint64(m.Version))
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.State.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBondAmount", wireType)
			}
			m.MinBondAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinBondAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReporters", wireType)
			}
			m.MaxReporters = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReporters |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReports", wireType)
			}
			m.MaxReports = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReports |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRewardHistory", wireType)
			}
			m.MaxRewardHistory = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRewardHistory |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReportIdBytes", wireType)
			}
			m.MaxReportIdBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReportIdBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReportTypeBytes", wireType)
			}
			m.MaxReportTypeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReportTypeBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSubjectBytes", wireType)
			}
			m.MaxSubjectBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSubjectBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPayloadHashBytes", wireType)
			}
			m.MaxPayloadHashBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPayloadHashBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPayloadBytes", wireType)
			}
			m.MaxPayloadBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPayloadBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengePeriodBlocks", wireType)
			}
			m.ChallengePeriodBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengePeriodBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaliciousSlashBps", wireType)
			}
			m.MaliciousSlashBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaliciousSlashBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialScore", wireType)
			}
			m.InitialScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialScore |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedScoreDelta", wireType)
			}
			m.AcceptedScoreDelta = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AcceptedScoreDelta |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedScoreDelta", wireType)
			}
			m.RejectedScoreDelta = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RejectedScoreDelta |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRewardAmount", wireType)
			}
			m.MaxRewardAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRewardAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReporterReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReporterReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReporterReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Claimed = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedAt", wireType)
			}
			m.ClaimedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReporterRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReporterRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReporterRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReporterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondedAmount", wireType)
			}
			m.BondedAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondedAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterScore", wireType)
			}
			m.ReporterScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReporterScore |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedReports", wireType)
			}
			m.AcceptedReports = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AcceptedReports |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedReports", wireType)
			}
			m.RejectedReports = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RejectedReports |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashedReporterBond", wireType)
			}
			m.SlashedReporterBond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashedReporterBond |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingStartHeight", wireType)
			}
			m.UnbondingStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingStartHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingCompleteHeight", wireType)
			}
			m.UnbondingCompleteHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingCompleteHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardHistory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardHistory = append(m.RewardHistory, ReporterReward{})
			if err := m.RewardHistory[len(m.RewardHistory)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReportRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReportRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReportRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReporterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayloadHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadSizeBytes", wireType)
			}
			m.PayloadSizeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PayloadSizeBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedHeight", wireType)
			}
			m.SubmittedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmittedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedHeight", wireType)
			}
			m.FinalizedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAmount", wireType)
			}
			m.RewardAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardClaimed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RewardClaimed = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashAmount", wireType)
			}
			m.SlashAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *State) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: State: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: State: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reporters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reporters = append(m.Reporters, ReporterRecord{})
			if err := m.Reporters[len(m.Reporters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reports = append(m.Reports, ReportRecord{})
			if err := m.Reports[len(m.Reports)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
