// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: l1/scheduler/v1/tx.proto

package schedulerv1

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateParams struct {
	Authority       string          `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params          Params          `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
	SchedulerParams SchedulerParams `protobuf:"bytes,3,opt,name=scheduler_params,json=schedulerParams,proto3" json:"scheduler_params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *MsgUpdateParams) GetSchedulerParams() SchedulerParams {
	if m != nil {
		return m.SchedulerParams
	}
	return SchedulerParams{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgRegisterScheduledJob struct {
	Authority string       `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Job       ScheduledJob `protobuf:"bytes,2,opt,name=job,proto3" json:"job"`
}

func (m *MsgRegisterScheduledJob) Reset()         { *m = MsgRegisterScheduledJob{} }
func (m *MsgRegisterScheduledJob) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterScheduledJob) ProtoMessage()    {}
func (*MsgRegisterScheduledJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{2}
}
func (m *MsgRegisterScheduledJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterScheduledJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterScheduledJob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterScheduledJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterScheduledJob.Merge(m, src)
}
func (m *MsgRegisterScheduledJob) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterScheduledJob) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterScheduledJob.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterScheduledJob proto.InternalMessageInfo

func (m *MsgRegisterScheduledJob) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRegisterScheduledJob) GetJob() ScheduledJob {
	if m != nil {
		return m.Job
	}
	return ScheduledJob{}
}

type MsgRegisterScheduledJobResponse struct {
}

func (m *MsgRegisterScheduledJobResponse) Reset()         { *m = MsgRegisterScheduledJobResponse{} }
func (m *MsgRegisterScheduledJobResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterScheduledJobResponse) ProtoMessage()    {}
func (*MsgRegisterScheduledJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{3}
}
func (m *MsgRegisterScheduledJobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterScheduledJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterScheduledJobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterScheduledJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterScheduledJobResponse.Merge(m, src)
}
func (m *MsgRegisterScheduledJobResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterScheduledJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterScheduledJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterScheduledJobResponse proto.InternalMessageInfo

type MsgPauseScheduledJob struct {
	Authority   string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	OwnerModule string `protobuf:"bytes,2,opt,name=owner_module,json=ownerModule,proto3" json:"owner_module,omitempty"`
	JobId       string `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (m *MsgPauseScheduledJob) Reset()         { *m = MsgPauseScheduledJob{} }
func (m *MsgPauseScheduledJob) String() string { return proto.CompactTextString(m) }
func (*MsgPauseScheduledJob) ProtoMessage()    {}
func (*MsgPauseScheduledJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{4}
}
func (m *MsgPauseScheduledJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseScheduledJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseScheduledJob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseScheduledJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseScheduledJob.Merge(m, src)
}
func (m *MsgPauseScheduledJob) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseScheduledJob) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseScheduledJob.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseScheduledJob proto.InternalMessageInfo

func (m *MsgPauseScheduledJob) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgPauseScheduledJob) GetOwnerModule() string {
	if m != nil {
		return m.OwnerModule
	}
	return ""
}

func (m *MsgPauseScheduledJob) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type MsgPauseScheduledJobResponse struct {
}

func (m *MsgPauseScheduledJobResponse) Reset()         { *m = MsgPauseScheduledJobResponse{} }
func (m *MsgPauseScheduledJobResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPauseScheduledJobResponse) ProtoMessage()    {}
func (*MsgPauseScheduledJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{5}
}
func (m *MsgPauseScheduledJobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseScheduledJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseScheduledJobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseScheduledJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseScheduledJobResponse.Merge(m, src)
}
func (m *MsgPauseScheduledJobResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseScheduledJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseScheduledJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseScheduledJobResponse proto.InternalMessageInfo

type MsgResumeScheduledJob struct {
	Authority   string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	OwnerModule string `protobuf:"bytes,2,opt,name=owner_module,json=ownerModule,proto3" json:"owner_module,omitempty"`
	JobId       string `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (m *MsgResumeScheduledJob) Reset()         { *m = MsgResumeScheduledJob{} }
func (m *MsgResumeScheduledJob) String() string { return proto.CompactTextString(m) }
func (*MsgResumeScheduledJob) ProtoMessage()    {}
func (*MsgResumeScheduledJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{6}
}
func (m *MsgResumeScheduledJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResumeScheduledJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResumeScheduledJob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResumeScheduledJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResumeScheduledJob.Merge(m, src)
}
func (m *MsgResumeScheduledJob) XXX_Size() int {
	return m.Size()
}
func (m *MsgResumeScheduledJob) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResumeScheduledJob.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResumeScheduledJob proto.InternalMessageInfo

func (m *MsgResumeScheduledJob) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgResumeScheduledJob) GetOwnerModule() string {
	if m != nil {
		return m.OwnerModule
	}
	return ""
}

func (m *MsgResumeScheduledJob) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type MsgResumeScheduledJobResponse struct {
}

func (m *MsgResumeScheduledJobResponse) Reset()         { *m = MsgResumeScheduledJobResponse{} }
func (m *MsgResumeScheduledJobResponse) String() string { return proto.CompactTextString(m) }
func (*MsgResumeScheduledJobResponse) ProtoMessage()    {}
func (*MsgResumeScheduledJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{7}
}
func (m *MsgResumeScheduledJobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResumeScheduledJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResumeScheduledJobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResumeScheduledJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResumeScheduledJobResponse.Merge(m, src)
}
func (m *MsgResumeScheduledJobResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgResumeScheduledJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResumeScheduledJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResumeScheduledJobResponse proto.InternalMessageInfo

type MsgCancelScheduledJob struct {
	Authority   string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	OwnerModule string `protobuf:"bytes,2,opt,name=owner_module,json=ownerModule,proto3" json:"owner_module,omitempty"`
	JobId       string `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (m *MsgCancelScheduledJob) Reset()         { *m = MsgCancelScheduledJob{} }
func (m *MsgCancelScheduledJob) String() string { return proto.CompactTextString(m) }
func (*MsgCancelScheduledJob) ProtoMessage()    {}
func (*MsgCancelScheduledJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{8}
}
func (m *MsgCancelScheduledJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelScheduledJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelScheduledJob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelScheduledJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelScheduledJob.Merge(m, src)
}
func (m *MsgCancelScheduledJob) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelScheduledJob) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelScheduledJob.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelScheduledJob proto.InternalMessageInfo

func (m *MsgCancelScheduledJob) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgCancelScheduledJob) GetOwnerModule() string {
	if m != nil {
		return m.OwnerModule
	}
	return ""
}

func (m *MsgCancelScheduledJob) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type MsgCancelScheduledJobResponse struct {
}

func (m *MsgCancelScheduledJobResponse) Reset()         { *m = MsgCancelScheduledJobResponse{} }
func (m *MsgCancelScheduledJobResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelScheduledJobResponse) ProtoMessage()    {}
func (*MsgCancelScheduledJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{9}
}
func (m *MsgCancelScheduledJobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelScheduledJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelScheduledJobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelScheduledJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelScheduledJobResponse.Merge(m, src)
}
func (m *MsgCancelScheduledJobResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelScheduledJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelScheduledJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelScheduledJobResponse proto.InternalMessageInfo

type MsgExecuteDueJobs struct {
	Authority     string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	CurrentHeight uint64 `protobuf:"varint,2,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
}

func (m *MsgExecuteDueJobs) Reset()         { *m = MsgExecuteDueJobs{} }
func (m *MsgExecuteDueJobs) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteDueJobs) ProtoMessage()    {}
func (*MsgExecuteDueJobs) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{10}
}
func (m *MsgExecuteDueJobs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteDueJobs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteDueJobs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteDueJobs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteDueJobs.Merge(m, src)
}
func (m *MsgExecuteDueJobs) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteDueJobs) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteDueJobs.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteDueJobs proto.InternalMessageInfo

func (m *MsgExecuteDueJobs) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgExecuteDueJobs) GetCurrentHeight() uint64 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

type MsgExecuteDueJobsResponse struct {
	Result ExecutionBatchResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
}

func (m *MsgExecuteDueJobsResponse) Reset()         { *m = MsgExecuteDueJobsResponse{} }
func (m *MsgExecuteDueJobsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteDueJobsResponse) ProtoMessage()    {}
func (*MsgExecuteDueJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{11}
}
func (m *MsgExecuteDueJobsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteDueJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteDueJobsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteDueJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteDueJobsResponse.Merge(m, src)
}
func (m *MsgExecuteDueJobsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteDueJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteDueJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteDueJobsResponse proto.InternalMessageInfo

func (m *MsgExecuteDueJobsResponse) GetResult() ExecutionBatchResult {
	if m != nil {
		return m.Result
	}
	return ExecutionBatchResult{}
}

type ExecutionBatchResult struct {
	Height       uint64             `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	ExecutedJobs uint32             `protobuf:"varint,2,opt,name=executed_jobs,json=executedJobs,proto3" json:"executed_jobs,omitempty"`
	SkippedJobs  uint32             `protobuf:"varint,3,opt,name=skipped_jobs,json=skippedJobs,proto3" json:"skipped_jobs,omitempty"`
	GasReserved  uint64             `protobuf:"varint,4,opt,name=gas_reserved,json=gasReserved,proto3" json:"gas_reserved,omitempty"`
	GasUsed      uint64             `protobuf:"varint,5,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	History      []JobHistoryRecord `protobuf:"bytes,6,rep,name=history,proto3" json:"history"`
	RemainingDue []ScheduledJob     `protobuf:"bytes,7,rep,name=remaining_due,json=remainingDue,proto3" json:"remaining_due"`
}

func (m *ExecutionBatchResult) Reset()         { *m = ExecutionBatchResult{} }
func (m *ExecutionBatchResult) String() string { return proto.CompactTextString(m) }
func (*ExecutionBatchResult) ProtoMessage()    {}
func (*ExecutionBatchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_442a060bb73432fa, []int{12}
}
func (m *ExecutionBatchResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecutionBatchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecutionBatchResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecutionBatchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionBatchResult.Merge(m, src)
}
func (m *ExecutionBatchResult) XXX_Size() int {
	return m.Size()
}
func (m *ExecutionBatchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionBatchResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionBatchResult proto.InternalMessageInfo

func (m *ExecutionBatchResult) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ExecutionBatchResult) GetExecutedJobs() uint32 {
	if m != nil {
		return m.ExecutedJobs
	}
	return 0
}

func (m *ExecutionBatchResult) GetSkippedJobs() uint32 {
	if m != nil {
		return m.SkippedJobs
	}
	return 0
}

func (m *ExecutionBatchResult) GetGasReserved() uint64 {
	if m != nil {
		return m.GasReserved
	}
	return 0
}

func (m *ExecutionBatchResult) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *ExecutionBatchResult) GetHistory() []JobHistoryRecord {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *ExecutionBatchResult) GetRemainingDue() []ScheduledJob {
	if m != nil {
		return m.RemainingDue
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "l1.scheduler.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "l1.scheduler.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgRegisterScheduledJob)(nil), "l1.scheduler.v1.MsgRegisterScheduledJob")
	proto.RegisterType((*MsgRegisterScheduledJobResponse)(nil), "l1.scheduler.v1.MsgRegisterScheduledJobResponse")
	proto.RegisterType((*MsgPauseScheduledJob)(nil), "l1.scheduler.v1.MsgPauseScheduledJob")
	proto.RegisterType((*MsgPauseScheduledJobResponse)(nil), "l1.scheduler.v1.MsgPauseScheduledJobResponse")
	proto.RegisterType((*MsgResumeScheduledJob)(nil), "l1.scheduler.v1.MsgResumeScheduledJob")
	proto.RegisterType((*MsgResumeScheduledJobResponse)(nil), "l1.scheduler.v1.MsgResumeScheduledJobResponse")
	proto.RegisterType((*MsgCancelScheduledJob)(nil), "l1.scheduler.v1.MsgCancelScheduledJob")
	proto.RegisterType((*MsgCancelScheduledJobResponse)(nil), "l1.scheduler.v1.MsgCancelScheduledJobResponse")
	proto.RegisterType((*MsgExecuteDueJobs)(nil), "l1.scheduler.v1.MsgExecuteDueJobs")
	proto.RegisterType((*MsgExecuteDueJobsResponse)(nil), "l1.scheduler.v1.MsgExecuteDueJobsResponse")
	proto.RegisterType((*ExecutionBatchResult)(nil), "l1.scheduler.v1.ExecutionBatchResult")
}

func init() { proto.RegisterFile("l1/scheduler/v1/tx.proto", fileDescriptor_442a060bb73432fa) }

var fileDescriptor_442a060bb73432fa = []byte{
	// 765 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x96, 0x3d, 0x4f, 0xdb, 0x40,
	0x18, 0xc7, 0x63, 0x42, 0x42, 0x73, 0x49, 0xa0, 0x58, 0xa1, 0x04, 0x0b, 0x42, 0x92, 0x8a, 0x2a,
	0x42, 0x22, 0x6e, 0x52, 0x75, 0xa1, 0x53, 0x81, 0x4a, 0x14, 0x29, 0x12, 0x75, 0xcb, 0xc2, 0x12,
	0xfc, 0x72, 0x3a, 0x3b, 0xb5, 0x7d, 0xd1, 0x9d, 0x9d, 0xc2, 0xd2, 0x56, 0x95, 0xba, 0xf7, 0xa3,
	0xf0, 0x15, 0xba, 0xd1, 0x8d, 0xb1, 0x53, 0x55, 0xc1, 0xc0, 0xd7, 0xa8, 0x7c, 0x7e, 0x81, 0xd8,
	0x46, 0x49, 0x27, 0x36, 0xfb, 0xb9, 0xdf, 0xfd, 0x9f, 0xdf, 0x39, 0xf1, 0x23, 0x83, 0xaa, 0xd9,
	0x11, 0xa9, 0xaa, 0x43, 0xcd, 0x35, 0x21, 0x11, 0x47, 0x1d, 0xd1, 0x39, 0x6d, 0x0f, 0x09, 0x76,
	0x30, 0xbf, 0x60, 0x76, 0xda, 0xd1, 0x4a, 0x7b, 0xd4, 0x11, 0x96, 0x55, 0x4c, 0x2d, 0x4c, 0x45,
	0x8b, 0x22, 0x0f, 0xb4, 0x28, 0xf2, 0x49, 0xa1, 0x82, 0x30, 0xc2, 0xec, 0x52, 0xf4, 0xae, 0x82,
	0xea, 0x5a, 0x3c, 0x19, 0x41, 0x1b, 0x52, 0x83, 0xfa, 0xcb, 0xcd, 0x5f, 0x1c, 0x58, 0xe8, 0x51,
	0x74, 0x34, 0xd4, 0x64, 0x07, 0x1e, 0xca, 0x44, 0xb6, 0x28, 0xbf, 0x0a, 0x0a, 0xb2, 0xeb, 0xe8,
	0x98, 0x18, 0xce, 0x59, 0x95, 0xab, 0x73, 0xad, 0x82, 0x74, 0x5b, 0xe0, 0x5f, 0x82, 0xfc, 0x90,
	0x71, 0xd5, 0x99, 0x3a, 0xd7, 0x2a, 0x76, 0x97, 0xdb, 0x31, 0xc3, 0xb6, 0x1f, 0xb3, 0x33, 0x7b,
	0xf1, 0x67, 0x3d, 0x23, 0x05, 0x30, 0xff, 0x0e, 0x3c, 0x8e, 0xa0, 0x7e, 0x10, 0x90, 0x65, 0x01,
	0xf5, 0x44, 0xc0, 0xfb, 0xf0, 0x66, 0x2c, 0x69, 0x81, 0x8e, 0x97, 0xb7, 0xe7, 0xbf, 0xdd, 0x9c,
	0x6f, 0xde, 0x9a, 0x35, 0x57, 0xc0, 0x72, 0xec, 0x28, 0x12, 0xa4, 0x43, 0x6c, 0x53, 0xd8, 0xfc,
	0xcc, 0x96, 0x24, 0x88, 0x0c, 0xea, 0x40, 0x12, 0xe6, 0x6b, 0x07, 0x58, 0x99, 0x78, 0xda, 0xec,
	0x00, 0x2b, 0xc1, 0x51, 0xd7, 0xee, 0x35, 0xf5, 0x92, 0x02, 0x4d, 0x8f, 0x4f, 0xa8, 0x35, 0xc0,
	0xfa, 0x3d, 0xfd, 0xef, 0x28, 0x56, 0x7a, 0x14, 0x1d, 0xca, 0x2e, 0x85, 0xff, 0xe1, 0xd7, 0x00,
	0x25, 0xfc, 0xc9, 0x86, 0xa4, 0x6f, 0x61, 0x6f, 0x07, 0x13, 0x2d, 0x48, 0x45, 0x56, 0xeb, 0xb1,
	0x12, 0xbf, 0x04, 0xf2, 0x03, 0xac, 0xf4, 0x0d, 0x8d, 0x3d, 0xef, 0x82, 0x94, 0x1b, 0x60, 0xe5,
	0xad, 0x96, 0x50, 0xac, 0x81, 0xd5, 0xb4, 0xfe, 0x91, 0xdf, 0x17, 0xb0, 0xc4, 0x8e, 0x40, 0x5d,
	0xeb, 0x61, 0x04, 0xd7, 0xc1, 0x5a, 0xaa, 0x40, 0xcc, 0x70, 0x57, 0xb6, 0x55, 0x68, 0x3e, 0xa0,
	0x61, 0x52, 0x20, 0x32, 0xd4, 0xc1, 0x62, 0x8f, 0xa2, 0x37, 0xa7, 0x50, 0x75, 0x1d, 0xb8, 0xe7,
	0xc2, 0x03, 0xac, 0x4c, 0x7a, 0xdd, 0x36, 0xc0, 0xbc, 0xea, 0x12, 0x02, 0x6d, 0xa7, 0xaf, 0x43,
	0x03, 0xe9, 0x0e, 0xf3, 0x9b, 0x95, 0xca, 0x41, 0x75, 0x9f, 0x15, 0x13, 0x2a, 0x27, 0x60, 0x25,
	0xd1, 0x29, 0xd4, 0xe0, 0x77, 0x41, 0x9e, 0x40, 0xea, 0x9a, 0x0e, 0x6b, 0x57, 0xec, 0x6e, 0x24,
	0xfe, 0xd7, 0xfe, 0x46, 0x03, 0xdb, 0x3b, 0xb2, 0xa3, 0xea, 0x12, 0x83, 0xc3, 0x17, 0xda, 0xdf,
	0xda, 0xfc, 0x39, 0x03, 0x2a, 0x69, 0x18, 0xff, 0x04, 0xe4, 0x03, 0x53, 0x8e, 0x99, 0x06, 0x77,
	0xfc, 0x53, 0x50, 0x86, 0xbe, 0x8f, 0xd6, 0x1f, 0x60, 0xc5, 0x9f, 0x1f, 0x65, 0xa9, 0x14, 0x16,
	0xd9, 0xc3, 0x68, 0x80, 0x12, 0xfd, 0x68, 0x0c, 0x87, 0x21, 0x93, 0x65, 0x4c, 0x31, 0xa8, 0x85,
	0x08, 0x92, 0x69, 0x9f, 0x40, 0x0a, 0xc9, 0x08, 0x6a, 0xd5, 0x59, 0xd6, 0xa5, 0x88, 0x64, 0xef,
	0x80, 0xac, 0xc4, 0xaf, 0x80, 0x47, 0x1e, 0xe2, 0x52, 0xa8, 0x55, 0x73, 0x6c, 0x79, 0x0e, 0xc9,
	0xf4, 0x88, 0x42, 0x8d, 0x7f, 0x0d, 0xe6, 0x74, 0x83, 0x3a, 0x98, 0x9c, 0x55, 0xf3, 0xf5, 0x6c,
	0xab, 0xd8, 0x6d, 0x24, 0x0e, 0x7f, 0x80, 0x95, 0x7d, 0x1f, 0x91, 0xa0, 0x8a, 0x89, 0x16, 0x1c,
	0x3c, 0xdc, 0xc7, 0xef, 0x83, 0x32, 0x81, 0x96, 0x6c, 0xd8, 0x86, 0x8d, 0xfa, 0x9a, 0x0b, 0xab,
	0x73, 0x2c, 0x68, 0xaa, 0xe9, 0x50, 0x8a, 0x76, 0xee, 0xb9, 0xb0, 0xfb, 0x3d, 0x07, 0xb2, 0x3d,
	0x8a, 0xf8, 0x63, 0x50, 0x1a, 0x9b, 0xc0, 0xc9, 0x91, 0x18, 0x1b, 0x6c, 0x42, 0x6b, 0x12, 0x11,
	0xfd, 0xd8, 0x04, 0x54, 0x52, 0xe7, 0x5e, 0x6a, 0x42, 0x1a, 0x29, 0x3c, 0x9f, 0x96, 0x8c, 0x7a,
	0x1a, 0x60, 0x31, 0x39, 0xc8, 0x36, 0xd2, 0x62, 0x12, 0x98, 0xb0, 0x35, 0x15, 0x16, 0xb5, 0x32,
	0x01, 0x9f, 0x32, 0x93, 0x9e, 0xa5, 0x2b, 0xc7, 0x39, 0xa1, 0x3d, 0x1d, 0x77, 0xb7, 0x5b, 0xca,
	0x7c, 0x49, 0xed, 0x96, 0xe4, 0xd2, 0xbb, 0xdd, 0x3f, 0x2e, 0xf8, 0x13, 0x30, 0x1f, 0x9b, 0x15,
	0xcd, 0xb4, 0x84, 0x71, 0x46, 0xd8, 0x9c, 0xcc, 0x84, 0x1d, 0x84, 0xdc, 0xd7, 0x9b, 0xf3, 0x4d,
	0x6e, 0xe7, 0xc3, 0xc5, 0x55, 0x8d, 0xbb, 0xbc, 0xaa, 0x71, 0x7f, 0xaf, 0x6a, 0xdc, 0x8f, 0xeb,
	0x5a, 0xe6, 0xf2, 0xba, 0x96, 0xf9, 0x7d, 0x5d, 0xcb, 0x1c, 0x6f, 0x23, 0xc3, 0xd1, 0x5d, 0xa5,
	0xad, 0x62, 0x4b, 0xa4, 0x78, 0x04, 0x09, 0x34, 0x90, 0xbd, 0x65, 0x76, 0x44, 0xb3, 0x23, 0xca,
	0x43, 0x43, 0x8c, 0x7d, 0x5d, 0xbc, 0x8a, 0x6e, 0x46, 0x1d, 0x25, 0xcf, 0x3e, 0x31, 0x5e, 0xfc,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0xce, 0x83, 0x23, 0xf3, 0xdd, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	RegisterScheduledJob(ctx context.Context, in *MsgRegisterScheduledJob, opts ...grpc.CallOption) (*MsgRegisterScheduledJobResponse, error)
	PauseScheduledJob(ctx context.Context, in *MsgPauseScheduledJob, opts ...grpc.CallOption) (*MsgPauseScheduledJobResponse, error)
	ResumeScheduledJob(ctx context.Context, in *MsgResumeScheduledJob, opts ...grpc.CallOption) (*MsgResumeScheduledJobResponse, error)
	CancelScheduledJob(ctx context.Context, in *MsgCancelScheduledJob, opts ...grpc.CallOption) (*MsgCancelScheduledJobResponse, error)
	ExecuteDueJobs(ctx context.Context, in *MsgExecuteDueJobs, opts ...grpc.CallOption) (*MsgExecuteDueJobsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/l1.scheduler.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterScheduledJob(ctx context.Context, in *MsgRegisterScheduledJob, opts ...grpc.CallOption) (*MsgRegisterScheduledJobResponse, error) {
	out := new(MsgRegisterScheduledJobResponse)
	err := c.cc.Invoke(ctx, "/l1.scheduler.v1.Msg/RegisterScheduledJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PauseScheduledJob(ctx context.Context, in *MsgPauseScheduledJob, opts ...grpc.CallOption) (*MsgPauseScheduledJobResponse, error) {
	out := new(MsgPauseScheduledJobResponse)
	err := c.cc.Invoke(ctx, "/l1.scheduler.v1.Msg/PauseScheduledJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ResumeScheduledJob(ctx context.Context, in *MsgResumeScheduledJob, opts ...grpc.CallOption) (*MsgResumeScheduledJobResponse, error) {
	out := new(MsgResumeScheduledJobResponse)
	err := c.cc.Invoke(ctx, "/l1.scheduler.v1.Msg/ResumeScheduledJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelScheduledJob(ctx context.Context, in *MsgCancelScheduledJob, opts ...grpc.CallOption) (*MsgCancelScheduledJobResponse, error) {
	out := new(MsgCancelScheduledJobResponse)
	err := c.cc.Invoke(ctx, "/l1.scheduler.v1.Msg/CancelScheduledJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExecuteDueJobs(ctx context.Context, in *MsgExecuteDueJobs, opts ...grpc.CallOption) (*MsgExecuteDueJobsResponse, error) {
	out := new(MsgExecuteDueJobsResponse)
	err := c.cc.Invoke(ctx, "/l1.scheduler.v1.Msg/ExecuteDueJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	RegisterScheduledJob(context.Context, *MsgRegisterScheduledJob) (*MsgRegisterScheduledJobResponse, error)
	PauseScheduledJob(context.Context, *MsgPauseScheduledJob) (*MsgPauseScheduledJobResponse, error)
	ResumeScheduledJob(context.Context, *MsgResumeScheduledJob) (*MsgResumeScheduledJobResponse, error)
	CancelScheduledJob(context.Context, *MsgCancelScheduledJob) (*MsgCancelScheduledJobResponse, error)
	ExecuteDueJobs(context.Context, *MsgExecuteDueJobs) (*MsgExecuteDueJobsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) RegisterScheduledJob(ctx context.Context, req *MsgRegisterScheduledJob) (*MsgRegisterScheduledJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterScheduledJob not implemented")
}
func (*UnimplementedMsgServer) PauseScheduledJob(ctx context.Context, req *MsgPauseScheduledJob) (*MsgPauseScheduledJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseScheduledJob not implemented")
}
func (*UnimplementedMsgServer) ResumeScheduledJob(ctx context.Context, req *MsgResumeScheduledJob) (*MsgResumeScheduledJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeScheduledJob not implemented")
}
func (*UnimplementedMsgServer) CancelScheduledJob(ctx context.Context, req *MsgCancelScheduledJob) (*MsgCancelScheduledJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelScheduledJob not implemented")
}
func (*UnimplementedMsgServer) ExecuteDueJobs(ctx context.Context, req *MsgExecuteDueJobs) (*MsgExecuteDueJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDueJobs not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.scheduler.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterScheduledJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterScheduledJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterScheduledJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.scheduler.v1.Msg/RegisterScheduledJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterScheduledJob(ctx, req.(*MsgRegisterScheduledJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PauseScheduledJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPauseScheduledJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PauseScheduledJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.scheduler.v1.Msg/PauseScheduledJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PauseScheduledJob(ctx, req.(*MsgPauseScheduledJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ResumeScheduledJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgResumeScheduledJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ResumeScheduledJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.scheduler.v1.Msg/ResumeScheduledJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ResumeScheduledJob(ctx, req.(*MsgResumeScheduledJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelScheduledJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelScheduledJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelScheduledJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.scheduler.v1.Msg/CancelScheduledJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelScheduledJob(ctx, req.(*MsgCancelScheduledJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExecuteDueJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecuteDueJobs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecuteDueJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/l1.scheduler.v1.Msg/ExecuteDueJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecuteDueJobs(ctx, req.(*MsgExecuteDueJobs))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "l1.scheduler.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterScheduledJob",
			Handler:    _Msg_RegisterScheduledJob_Handler,
		},
		{
			MethodName: "PauseScheduledJob",
			Handler:    _Msg_PauseScheduledJob_Handler,
		},
		{
			MethodName: "ResumeScheduledJob",
			Handler:    _Msg_ResumeScheduledJob_Handler,
		},
		{
			MethodName: "CancelScheduledJob",
			Handler:    _Msg_CancelScheduledJob_Handler,
		},
		{
			MethodName: "ExecuteDueJobs",
			Handler:    _Msg_ExecuteDueJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "l1/scheduler/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SchedulerParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterScheduledJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterScheduledJob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterScheduledJob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Job.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterScheduledJobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterScheduledJobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterScheduledJobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgPauseScheduledJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseScheduledJob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseScheduledJob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OwnerModule) > 0 {
		i -= len(m.OwnerModule)
		copy(dAtA[i:], m.OwnerModule)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OwnerModule)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPauseScheduledJobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseScheduledJobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseScheduledJobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgResumeScheduledJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResumeScheduledJob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResumeScheduledJob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OwnerModule) > 0 {
		i -= len(m.OwnerModule)
		copy(dAtA[i:], m.OwnerModule)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OwnerModule)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgResumeScheduledJobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResumeScheduledJobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResumeScheduledJobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelScheduledJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelScheduledJob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelScheduledJob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OwnerModule) > 0 {
		i -= len(m.OwnerModule)
		copy(dAtA[i:], m.OwnerModule)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OwnerModule)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelScheduledJobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelScheduledJobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelScheduledJobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgExecuteDueJobs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteDueJobs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteDueJobs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CurrentHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExecuteDueJobsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteDueJobsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteDueJobsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ExecutionBatchResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecutionBatchResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecutionBatchResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RemainingDue) > 0 {
		for iNdEx := len(m.RemainingDue) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RemainingDue[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.History) > 0 {
		for iNdEx := len(m.History) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.History[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.GasUsed != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GasUsed))
		i--
		dAtA[i] = 0x28
	}
	if m.GasReserved != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GasReserved))
		i--
		dAtA[i] = 0x20
	}
	if m.SkippedJobs != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SkippedJobs))
		i--
		dAtA[i] = 0x18
	}
	if m.ExecutedJobs != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExecutedJobs))
		i--
		dAtA[i] = 0x10
	}
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.SchedulerParams.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterScheduledJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Job.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRegisterScheduledJobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgPauseScheduledJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OwnerModule)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPauseScheduledJobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgResumeScheduledJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OwnerModule)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgResumeScheduledJobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelScheduledJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OwnerModule)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelScheduledJobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgExecuteDueJobs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.CurrentHeight != 0 {
		n += 1 + sovTx(uint64(m.CurrentHeight))
	}
	return n
}

func (m *MsgExecuteDueJobsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Result.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *ExecutionBatchResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	if m.ExecutedJobs != 0 {
		n += 1 + sovTx(uint64(m.ExecutedJobs))
	}
	if m.SkippedJobs != 0 {
		n += 1 + sovTx(uint64(m.SkippedJobs))
	}
	if m.GasReserved != 0 {
		n += 1 + sovTx(uint64(m.GasReserved))
	}
	if m.GasUsed != 0 {
		n += 1 + sovTx(uint64(m.GasUsed))
	}
	if len(m.History) > 0 {
		for _, e := range m.History {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.RemainingDue) > 0 {
		for _, e := range m.RemainingDue {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchedulerParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SchedulerParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterScheduledJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterScheduledJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterScheduledJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Job", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Job.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterScheduledJobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterScheduledJobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterScheduledJobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseScheduledJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseScheduledJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseScheduledJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerModule", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerModule = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseScheduledJobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseScheduledJobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseScheduledJobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResumeScheduledJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResumeScheduledJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResumeScheduledJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerModule", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerModule = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResumeScheduledJobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResumeScheduledJobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResumeScheduledJobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelScheduledJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelScheduledJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelScheduledJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerModule", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerModule = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelScheduledJobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelScheduledJobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelScheduledJobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteDueJobs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteDueJobs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteDueJobs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentHeight", wireType)
			}
			m.CurrentHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteDueJobsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteDueJobsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteDueJobsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionBatchResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionBatchResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionBatchResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutedJobs", wireType)
			}
			m.ExecutedJobs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutedJobs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkippedJobs", wireType)
			}
			m.SkippedJobs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SkippedJobs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasReserved", wireType)
			}
			m.GasReserved = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasReserved |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasUsed", wireType)
			}
			m.GasUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasUsed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field History", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.History = append(m.History, JobHistoryRecord{})
			if err := m.History[len(m.History)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingDue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemainingDue = append(m.RemainingDue, ScheduledJob{})
			if err := m.RemainingDue[len(m.RemainingDue)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
