// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: l1/config/v1/genesis.proto

package configv1

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Version uint64      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Params  Params      `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
	State   ConfigState `protobuf:"bytes,3,opt,name=state,proto3" json:"state"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_618501ee55a47ea6, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetState() ConfigState {
	if m != nil {
		return m.State
	}
	return ConfigState{}
}

type Params struct {
	Authority                 string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MaxEntries                uint32   `protobuf:"varint,2,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	MaxPendingChanges         uint32   `protobuf:"varint,3,opt,name=max_pending_changes,json=maxPendingChanges,proto3" json:"max_pending_changes,omitempty"`
	MaxKeyBytes               uint32   `protobuf:"varint,4,opt,name=max_key_bytes,json=maxKeyBytes,proto3" json:"max_key_bytes,omitempty"`
	MaxValueBytes             uint32   `protobuf:"varint,5,opt,name=max_value_bytes,json=maxValueBytes,proto3" json:"max_value_bytes,omitempty"`
	MaxChangeIdBytes          uint32   `protobuf:"varint,6,opt,name=max_change_id_bytes,json=maxChangeIdBytes,proto3" json:"max_change_id_bytes,omitempty"`
	BaseDenom                 string   `protobuf:"bytes,7,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty"`
	RequiredSystemAccountKeys []string `protobuf:"bytes,8,rep,name=required_system_account_keys,json=requiredSystemAccountKeys,proto3" json:"required_system_account_keys,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_618501ee55a47ea6, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Params) GetMaxEntries() uint32 {
	if m != nil {
		return m.MaxEntries
	}
	return 0
}

func (m *Params) GetMaxPendingChanges() uint32 {
	if m != nil {
		return m.MaxPendingChanges
	}
	return 0
}

func (m *Params) GetMaxKeyBytes() uint32 {
	if m != nil {
		return m.MaxKeyBytes
	}
	return 0
}

func (m *Params) GetMaxValueBytes() uint32 {
	if m != nil {
		return m.MaxValueBytes
	}
	return 0
}

func (m *Params) GetMaxChangeIdBytes() uint32 {
	if m != nil {
		return m.MaxChangeIdBytes
	}
	return 0
}

func (m *Params) GetBaseDenom() string {
	if m != nil {
		return m.BaseDenom
	}
	return ""
}

func (m *Params) GetRequiredSystemAccountKeys() []string {
	if m != nil {
		return m.RequiredSystemAccountKeys
	}
	return nil
}

type ConfigState struct {
	Entries        []ConfigEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries"`
	PendingChanges []ConfigChange `protobuf:"bytes,2,rep,name=pending_changes,json=pendingChanges,proto3" json:"pending_changes"`
}

func (m *ConfigState) Reset()         { *m = ConfigState{} }
func (m *ConfigState) String() string { return proto.CompactTextString(m) }
func (*ConfigState) ProtoMessage()    {}
func (*ConfigState) Descriptor() ([]byte, []int) {
	return fileDescriptor_618501ee55a47ea6, []int{2}
}
func (m *ConfigState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigState.Merge(m, src)
}
func (m *ConfigState) XXX_Size() int {
	return m.Size()
}
func (m *ConfigState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigState.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigState proto.InternalMessageInfo

func (m *ConfigState) GetEntries() []ConfigEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *ConfigState) GetPendingChanges() []ConfigChange {
	if m != nil {
		return m.PendingChanges
	}
	return nil
}

type ConfigEntry struct {
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Owner         string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Version       uint64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedHeight int64  `protobuf:"varint,5,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
}

func (m *ConfigEntry) Reset()         { *m = ConfigEntry{} }
func (m *ConfigEntry) String() string { return proto.CompactTextString(m) }
func (*ConfigEntry) ProtoMessage()    {}
func (*ConfigEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_618501ee55a47ea6, []int{3}
}
func (m *ConfigEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigEntry.Merge(m, src)
}
func (m *ConfigEntry) XXX_Size() int {
	return m.Size()
}
func (m *ConfigEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigEntry proto.InternalMessageInfo

func (m *ConfigEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ConfigEntry) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ConfigEntry) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigEntry) GetUpdatedHeight() int64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

type ConfigChange struct {
	Id                                  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                                 string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                               string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Operation                           string `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Status                              string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	SubmittedBy                         string `protobuf:"bytes,6,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	ApprovedBy                          string `protobuf:"bytes,7,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	RejectedBy                          string `protobuf:"bytes,8,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	CancelledBy                         string `protobuf:"bytes,9,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	ExecutedBy                          string `protobuf:"bytes,10,opt,name=executed_by,json=executedBy,proto3" json:"executed_by,omitempty"`
	Reason                              string `protobuf:"bytes,11,opt,name=reason,proto3" json:"reason,omitempty"`
	RequiresConstitutionalException     bool   `protobuf:"varint,12,opt,name=requires_constitutional_exception,json=requiresConstitutionalException,proto3" json:"requires_constitutional_exception,omitempty"`
	CreatedHeight                       int64  `protobuf:"varint,13,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	UpdatedHeight                       int64  `protobuf:"varint,14,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
	ExpectedPreviousVersion             uint64 `protobuf:"varint,15,opt,name=expected_previous_version,json=expectedPreviousVersion,proto3" json:"expected_previous_version,omitempty"`
	AllowMissingExpectedPreviousVersion bool   `protobuf:"varint,16,opt,name=allow_missing_expected_previous_version,json=allowMissingExpectedPreviousVersion,proto3" json:"allow_missing_expected_previous_version,omitempty"`
}

func (m *ConfigChange) Reset()         { *m = ConfigChange{} }
func (m *ConfigChange) String() string { return proto.CompactTextString(m) }
func (*ConfigChange) ProtoMessage()    {}
func (*ConfigChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_618501ee55a47ea6, []int{4}
}
func (m *ConfigChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigChange.Merge(m, src)
}
func (m *ConfigChange) XXX_Size() int {
	return m.Size()
}
func (m *ConfigChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigChange.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigChange proto.InternalMessageInfo

func (m *ConfigChange) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfigChange) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigChange) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ConfigChange) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *ConfigChange) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ConfigChange) GetSubmittedBy() string {
	if m != nil {
		return m.SubmittedBy
	}
	return ""
}

func (m *ConfigChange) GetApprovedBy() string {
	if m != nil {
		return m.ApprovedBy
	}
	return ""
}

func (m *ConfigChange) GetRejectedBy() string {
	if m != nil {
		return m.RejectedBy
	}
	return ""
}

func (m *ConfigChange) GetCancelledBy() string {
	if m != nil {
		return m.CancelledBy
	}
	return ""
}

func (m *ConfigChange) GetExecutedBy() string {
	if m != nil {
		return m.ExecutedBy
	}
	return ""
}

func (m *ConfigChange) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ConfigChange) GetRequiresConstitutionalException() bool {
	if m != nil {
		return m.RequiresConstitutionalException
	}
	return false
}

func (m *ConfigChange) GetCreatedHeight() int64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *ConfigChange) GetUpdatedHeight() int64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

func (m *ConfigChange) GetExpectedPreviousVersion() uint64 {
	if m != nil {
		return m.ExpectedPreviousVersion
	}
	return 0
}

func (m *ConfigChange) GetAllowMissingExpectedPreviousVersion() bool {
	if m != nil {
		return m.AllowMissingExpectedPreviousVersion
	}
	return false
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "l1.config.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "l1.config.v1.Params")
	proto.RegisterType((*ConfigState)(nil), "l1.config.v1.ConfigState")
	proto.RegisterType((*ConfigEntry)(nil), "l1.config.v1.ConfigEntry")
	proto.RegisterType((*ConfigChange)(nil), "l1.config.v1.ConfigChange")
}

func init() { proto.RegisterFile("l1/config/v1/genesis.proto", fileDescriptor_618501ee55a47ea6) }

var fileDescriptor_618501ee55a47ea6 = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xc7, 0xe3, 0x24, 0x4d, 0xeb, 0xc9, 0x4b, 0xcb, 0x50, 0x81, 0x5b, 0x95, 0x34, 0x1b, 0x04,
	0xe4, 0xb2, 0xb1, 0xb2, 0xc0, 0x01, 0x38, 0x20, 0x52, 0x2a, 0x58, 0x56, 0xa0, 0xca, 0x8b, 0xf6,
	0xc0, 0xc5, 0x9a, 0xd8, 0x0f, 0xce, 0xb0, 0xb6, 0xc7, 0x78, 0xc6, 0xde, 0xf8, 0x3b, 0x70, 0x40,
	0xe2, 0x4b, 0xed, 0x71, 0xc5, 0x89, 0x13, 0x42, 0xed, 0x89, 0x6f, 0x81, 0x66, 0x1e, 0xbb, 0x9b,
	0xa0, 0xec, 0xcd, 0xf3, 0x9f, 0xdf, 0x3c, 0x6f, 0xff, 0x47, 0x26, 0xe7, 0xf1, 0xc2, 0x0d, 0x44,
	0xfa, 0x33, 0x8f, 0xdc, 0x72, 0xe1, 0x46, 0x90, 0x82, 0xe4, 0x72, 0x9e, 0xe5, 0x42, 0x09, 0x3a,
	0x88, 0x17, 0x73, 0xbc, 0x9b, 0x97, 0x8b, 0xf3, 0xd3, 0x48, 0x44, 0xc2, 0x5c, 0xb8, 0xfa, 0x0b,
	0x99, 0xe9, 0x1f, 0x16, 0x19, 0x7c, 0x83, 0xaf, 0x9e, 0x2a, 0xa6, 0x80, 0x3a, 0xe4, 0xb0, 0x84,
	0x5c, 0x72, 0x91, 0x3a, 0xd6, 0xc4, 0x9a, 0x75, 0xbd, 0xe6, 0x48, 0x1f, 0x91, 0x5e, 0xc6, 0x72,
	0x96, 0x48, 0xa7, 0x3d, 0xb1, 0x66, 0xfd, 0x47, 0xa7, 0xf3, 0xed, 0xf8, 0xf3, 0x1b, 0x73, 0xb7,
	0xec, 0xbe, 0xfc, 0xfb, 0xb2, 0xe5, 0xd5, 0x24, 0xfd, 0x94, 0x1c, 0x48, 0x1d, 0xd6, 0xe9, 0x98,
	0x27, 0x67, 0xbb, 0x4f, 0xae, 0xcc, 0x97, 0xc9, 0x5b, 0xbf, 0x43, 0x7a, 0xfa, 0x67, 0x9b, 0xf4,
	0x30, 0x1e, 0xbd, 0x20, 0x36, 0x2b, 0xd4, 0x5a, 0xe4, 0x5c, 0x55, 0xa6, 0x22, 0xdb, 0x7b, 0x2d,
	0xd0, 0x4b, 0xd2, 0x4f, 0xd8, 0xc6, 0x87, 0x54, 0xe5, 0x1c, 0xb0, 0xb0, 0xa1, 0x47, 0x12, 0xb6,
	0xb9, 0x46, 0x85, 0xce, 0xc9, 0xdb, 0x1a, 0xc8, 0x20, 0x0d, 0x79, 0x1a, 0xf9, 0xc1, 0x9a, 0xa5,
	0x11, 0x48, 0x53, 0xce, 0xd0, 0x7b, 0x2b, 0x61, 0x9b, 0x1b, 0xbc, 0xb9, 0xc2, 0x0b, 0x3a, 0x25,
	0x43, 0xcd, 0x3f, 0x87, 0xca, 0x5f, 0x55, 0x0a, 0xa4, 0xd3, 0x35, 0xa4, 0xce, 0xf2, 0x04, 0xaa,
	0xa5, 0x96, 0xe8, 0x87, 0xe4, 0x58, 0x33, 0x25, 0x8b, 0x0b, 0xa8, 0xa9, 0x03, 0x43, 0xe9, 0xa7,
	0xcf, 0xb4, 0x8a, 0xdc, 0x43, 0xcc, 0x8d, 0x39, 0x7d, 0x1e, 0xd6, 0x6c, 0xcf, 0xb0, 0x27, 0x09,
	0xdb, 0x60, 0xd2, 0xc7, 0x21, 0xe2, 0xef, 0x11, 0xb2, 0x62, 0x12, 0xfc, 0x10, 0x52, 0x91, 0x38,
	0x87, 0xd8, 0xaa, 0x56, 0xbe, 0xd6, 0x02, 0xfd, 0x92, 0x5c, 0xe4, 0xf0, 0x6b, 0xc1, 0x73, 0x08,
	0x7d, 0x59, 0x49, 0x05, 0x89, 0xcf, 0x82, 0x40, 0x14, 0xa9, 0xd2, 0xd5, 0x4a, 0xe7, 0x68, 0xd2,
	0x99, 0xd9, 0xde, 0x59, 0xc3, 0x3c, 0x35, 0xc8, 0x57, 0x48, 0x3c, 0x81, 0x4a, 0x6a, 0xab, 0xfb,
	0x5b, 0x13, 0xa7, 0x9f, 0x91, 0xc3, 0x66, 0x6e, 0xd6, 0xa4, 0xf3, 0x26, 0x77, 0xf4, 0x20, 0xab,
	0xda, 0x9d, 0x86, 0xa7, 0x8f, 0xc9, 0xf1, 0xff, 0x27, 0xda, 0x36, 0x21, 0xce, 0xf7, 0x85, 0xc0,
	0x36, 0xeb, 0x18, 0xa3, 0x6c, 0x67, 0xe0, 0xd3, 0xdf, 0xee, 0xab, 0x32, 0x99, 0xe8, 0x09, 0xe9,
	0x3c, 0x87, 0xc6, 0x69, 0xfd, 0x49, 0x4f, 0xc9, 0x81, 0x19, 0xb5, 0x71, 0xd7, 0xf6, 0xf0, 0xa0,
	0x55, 0xf1, 0x22, 0x85, 0xdc, 0x58, 0x69, 0x7b, 0x78, 0xd8, 0xde, 0xde, 0xee, 0xee, 0xf6, 0x7e,
	0x40, 0x46, 0x45, 0x16, 0x32, 0x05, 0xa1, 0xbf, 0x06, 0x1e, 0xad, 0x95, 0xf1, 0xac, 0xe3, 0x0d,
	0x6b, 0xf5, 0x5b, 0x23, 0x4e, 0xff, 0xed, 0x92, 0xc1, 0x76, 0xd5, 0x74, 0x44, 0xda, 0x3c, 0xac,
	0xcb, 0x69, 0xf3, 0xb0, 0xa9, 0xaf, 0xbd, 0xa7, 0xbe, 0xce, 0x76, 0x7d, 0x17, 0xc4, 0x16, 0x19,
	0xe4, 0x4c, 0x35, 0xb5, 0xd8, 0xde, 0x6b, 0x81, 0xbe, 0x43, 0x7a, 0x7a, 0xd3, 0x0b, 0xdc, 0x1c,
	0xdb, 0xab, 0x4f, 0xf4, 0x01, 0x19, 0xc8, 0x62, 0x95, 0x70, 0xa5, 0xeb, 0x5c, 0x55, 0x66, 0x57,
	0x6c, 0xaf, 0x7f, 0xaf, 0x2d, 0xcd, 0xca, 0xb3, 0x2c, 0xcb, 0x45, 0x89, 0x04, 0xee, 0x09, 0x69,
	0x24, 0x04, 0x72, 0xf8, 0x05, 0x82, 0x3a, 0xc4, 0x11, 0x02, 0x8d, 0xb4, 0xac, 0x74, 0x92, 0x80,
	0xa5, 0x01, 0xc4, 0x31, 0x12, 0x36, 0x26, 0xb9, 0xd7, 0x30, 0x06, 0x6c, 0x20, 0x28, 0xea, 0x18,
	0x04, 0x63, 0x34, 0xd2, 0xb2, 0xd2, 0x0d, 0xe4, 0xc0, 0xa4, 0x48, 0x9d, 0x3e, 0x36, 0x80, 0x27,
	0xfa, 0x1d, 0x79, 0x50, 0x6f, 0xa0, 0xf4, 0x03, 0x91, 0x4a, 0xc5, 0x55, 0xa1, 0x3b, 0x66, 0xb1,
	0x0f, 0x9b, 0x00, 0x32, 0x33, 0x8e, 0xc1, 0xc4, 0x9a, 0x1d, 0x79, 0x97, 0x0d, 0x78, 0xb5, 0xc3,
	0x5d, 0x37, 0x98, 0xb6, 0x2c, 0xc8, 0x61, 0xdb, 0xb2, 0x21, 0x5a, 0x56, 0xab, 0x68, 0xd9, 0x1e,
	0x67, 0x47, 0x7b, 0x9c, 0xa5, 0x9f, 0x93, 0x33, 0xd8, 0x64, 0x38, 0x96, 0x2c, 0x87, 0x92, 0x8b,
	0x42, 0xfa, 0xcd, 0xb2, 0x1c, 0x9b, 0x65, 0x79, 0xb7, 0x01, 0x6e, 0xea, 0xfb, 0x67, 0xf5, 0xf2,
	0xfc, 0x48, 0x3e, 0x62, 0x71, 0x2c, 0x5e, 0xf8, 0x09, 0x97, 0x52, 0x6f, 0xfd, 0x9b, 0x23, 0x9d,
	0x98, 0xde, 0xde, 0x37, 0xf8, 0xf7, 0x48, 0x5f, 0xef, 0x8f, 0xba, 0xfc, 0xe1, 0xe5, 0xed, 0xd8,
	0x7a, 0x75, 0x3b, 0xb6, 0xfe, 0xb9, 0x1d, 0x5b, 0xbf, 0xdf, 0x8d, 0x5b, 0xaf, 0xee, 0xc6, 0xad,
	0xbf, 0xee, 0xc6, 0xad, 0x9f, 0x3e, 0x89, 0xb8, 0x5a, 0x17, 0xab, 0x79, 0x20, 0x12, 0x57, 0x8a,
	0x12, 0x72, 0xe0, 0x51, 0xfa, 0x30, 0x5e, 0xb8, 0xf1, 0xc2, 0x65, 0x19, 0x77, 0xb7, 0x7f, 0xfa,
	0x5f, 0xe0, 0x57, 0xb9, 0x58, 0xf5, 0xcc, 0x2f, 0xfd, 0xe3, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x97, 0x30, 0x5d, 0x4a, 0x14, 0x06, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Version != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequiredSystemAccountKeys) > 0 {
		for iNdEx := len(m.RequiredSystemAccountKeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RequiredSystemAccountKeys[iNdEx])
			copy(dAtA[i:], m.RequiredSystemAccountKeys[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.RequiredSystemAccountKeys[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.BaseDenom) > 0 {
		i -= len(m.BaseDenom)
		copy(dAtA[i:], m.BaseDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.BaseDenom)))
		i--
		dAtA[i] = 0x3a
	}
	if m.MaxChangeIdBytes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxChangeIdBytes))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxValueBytes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxValueBytes))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxKeyBytes != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxKeyBytes))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxPendingChanges != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxPendingChanges))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxEntries != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxEntries))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConfigState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfigState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PendingChanges) > 0 {
		for iNdEx := len(m.PendingChanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingChanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ConfigEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfigEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.Version != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConfigChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfigChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AllowMissingExpectedPreviousVersion {
		i--
		if m.AllowMissingExpectedPreviousVersion {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.ExpectedPreviousVersion != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ExpectedPreviousVersion))
		i--
		dAtA[i] = 0x78
	}
	if m.UpdatedHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x70
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x68
	}
	if m.RequiresConstitutionalException {
		i--
		if m.RequiresConstitutionalException {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ExecutedBy) > 0 {
		i -= len(m.ExecutedBy)
		copy(dAtA[i:], m.ExecutedBy)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ExecutedBy)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.CancelledBy) > 0 {
		i -= len(m.CancelledBy)
		copy(dAtA[i:], m.CancelledBy)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.CancelledBy)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.RejectedBy) > 0 {
		i -= len(m.RejectedBy)
		copy(dAtA[i:], m.RejectedBy)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.RejectedBy)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ApprovedBy) > 0 {
		i -= len(m.ApprovedBy)
		copy(dAtA[i:], m.ApprovedBy)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ApprovedBy)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SubmittedBy) > 0 {
		i -= len(m.SubmittedBy)
		copy(dAtA[i:], m.SubmittedBy)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.SubmittedBy)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Operation) > 0 {
		i -= len(m.Operation)
		copy(dAtA[i:], m.Operation)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Operation)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovGenesis(uint64(m.Version))
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.State.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.MaxEntries != 0 {
		n += 1 + sovGenesis(uint64(m.MaxEntries))
	}
	if m.MaxPendingChanges != 0 {
		n += 1 + sovGenesis(uint64(m.MaxPendingChanges))
	}
	if m.MaxKeyBytes != 0 {
		n += 1 + sovGenesis(uint64(m.MaxKeyBytes))
	}
	if m.MaxValueBytes != 0 {
		n += 1 + sovGenesis(uint64(m.MaxValueBytes))
	}
	if m.MaxChangeIdBytes != 0 {
		n += 1 + sovGenesis(uint64(m.MaxChangeIdBytes))
	}
	l = len(m.BaseDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.RequiredSystemAccountKeys) > 0 {
		for _, s := range m.RequiredSystemAccountKeys {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *ConfigState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingChanges) > 0 {
		for _, e := range m.PendingChanges {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *ConfigEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovGenesis(uint64(m.Version))
	}
	if m.UpdatedHeight != 0 {
		n += 1 + sovGenesis(uint64(m.UpdatedHeight))
	}
	return n
}

func (m *ConfigChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Operation)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.SubmittedBy)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ApprovedBy)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.RejectedBy)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.CancelledBy)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ExecutedBy)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.RequiresConstitutionalException {
		n += 2
	}
	if m.CreatedHeight != 0 {
		n += 1 + sovGenesis(uint64(m.CreatedHeight))
	}
	if m.UpdatedHeight != 0 {
		n += 1 + sovGenesis(uint64(m.UpdatedHeight))
	}
	if m.ExpectedPreviousVersion != 0 {
		n += 1 + sovGenesis(uint64(m.ExpectedPreviousVersion))
	}
	if m.AllowMissingExpectedPreviousVersion {
		n += 3
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxEntries", wireType)
			}
			m.MaxEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxEntries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPendingChanges", wireType)
			}
			m.MaxPendingChanges = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPendingChanges |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxKeyBytes", wireType)
			}
			m.MaxKeyBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxKeyBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxValueBytes", wireType)
			}
			m.MaxValueBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxValueBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxChangeIdBytes", wireType)
			}
			m.MaxChangeIdBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxChangeIdBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredSystemAccountKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequiredSystemAccountKeys = append(m.RequiredSystemAccountKeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, ConfigEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingChanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingChanges = append(m.PendingChanges, ConfigChange{})
			if err := m.PendingChanges[len(m.PendingChanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubmittedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApprovedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RejectedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelledBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CancelledBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecutedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiresConstitutionalException", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequiresConstitutionalException = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedPreviousVersion", wireType)
			}
			m.ExpectedPreviousVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpectedPreviousVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowMissingExpectedPreviousVersion", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowMissingExpectedPreviousVersion = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
