// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: l1/actorregistry/v1/genesis.proto

package actorregistryv1

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	Enabled               bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TestnetProfile        bool   `protobuf:"varint,2,opt,name=testnet_profile,json=testnetProfile,proto3" json:"testnet_profile,omitempty"`
	ProductionVersionGate string `protobuf:"bytes,3,opt,name=production_version_gate,json=productionVersionGate,proto3" json:"production_version_gate,omitempty"`
	Authority             string `protobuf:"bytes,4,opt,name=authority,proto3" json:"authority,omitempty"`
	DefaultQueryLimit     uint64 `protobuf:"varint,5,opt,name=default_query_limit,json=defaultQueryLimit,proto3" json:"default_query_limit,omitempty"`
	MaxQueryLimit         uint64 `protobuf:"varint,6,opt,name=max_query_limit,json=maxQueryLimit,proto3" json:"max_query_limit,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b1bb8f3b48f62, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Params) GetTestnetProfile() bool {
	if m != nil {
		return m.TestnetProfile
	}
	return false
}

func (m *Params) GetProductionVersionGate() string {
	if m != nil {
		return m.ProductionVersionGate
	}
	return ""
}

func (m *Params) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Params) GetDefaultQueryLimit() uint64 {
	if m != nil {
		return m.DefaultQueryLimit
	}
	return 0
}

func (m *Params) GetMaxQueryLimit() uint64 {
	if m != nil {
		return m.MaxQueryLimit
	}
	return 0
}

type ActorRegistryParams struct {
	MaxActors             uint32 `protobuf:"varint,1,opt,name=max_actors,json=maxActors,proto3" json:"max_actors,omitempty"`
	MaxCapabilities       uint32 `protobuf:"varint,2,opt,name=max_capabilities,json=maxCapabilities,proto3" json:"max_capabilities,omitempty"`
	DeletedValuePolicy    string `protobuf:"bytes,3,opt,name=deleted_value_policy,json=deletedValuePolicy,proto3" json:"deleted_value_policy,omitempty"`
	DeletedValueRedirect  string `protobuf:"bytes,4,opt,name=deleted_value_redirect,json=deletedValueRedirect,proto3" json:"deleted_value_redirect,omitempty"`
	AllowDeletedValueSend bool   `protobuf:"varint,5,opt,name=allow_deleted_value_send,json=allowDeletedValueSend,proto3" json:"allow_deleted_value_send,omitempty"`
}

func (m *ActorRegistryParams) Reset()         { *m = ActorRegistryParams{} }
func (m *ActorRegistryParams) String() string { return proto.CompactTextString(m) }
func (*ActorRegistryParams) ProtoMessage()    {}
func (*ActorRegistryParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b1bb8f3b48f62, []int{1}
}
func (m *ActorRegistryParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActorRegistryParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActorRegistryParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActorRegistryParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorRegistryParams.Merge(m, src)
}
func (m *ActorRegistryParams) XXX_Size() int {
	return m.Size()
}
func (m *ActorRegistryParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorRegistryParams.DiscardUnknown(m)
}

var xxx_messageInfo_ActorRegistryParams proto.InternalMessageInfo

func (m *ActorRegistryParams) GetMaxActors() uint32 {
	if m != nil {
		return m.MaxActors
	}
	return 0
}

func (m *ActorRegistryParams) GetMaxCapabilities() uint32 {
	if m != nil {
		return m.MaxCapabilities
	}
	return 0
}

func (m *ActorRegistryParams) GetDeletedValuePolicy() string {
	if m != nil {
		return m.DeletedValuePolicy
	}
	return ""
}

func (m *ActorRegistryParams) GetDeletedValueRedirect() string {
	if m != nil {
		return m.DeletedValueRedirect
	}
	return ""
}

func (m *ActorRegistryParams) GetAllowDeletedValueSend() bool {
	if m != nil {
		return m.AllowDeletedValueSend
	}
	return false
}

type ActorRegistryState struct {
	Actors     []ActorRecord          `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors"`
	CodeStore  []CodeRecord           `protobuf:"bytes,2,rep,name=code_store,json=codeStore,proto3" json:"code_store"`
	Migrations []ActorMigrationRecord `protobuf:"bytes,3,rep,name=migrations,proto3" json:"migrations"`
}

func (m *ActorRegistryState) Reset()         { *m = ActorRegistryState{} }
func (m *ActorRegistryState) String() string { return proto.CompactTextString(m) }
func (*ActorRegistryState) ProtoMessage()    {}
func (*ActorRegistryState) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b1bb8f3b48f62, []int{2}
}
func (m *ActorRegistryState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActorRegistryState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActorRegistryState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActorRegistryState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorRegistryState.Merge(m, src)
}
func (m *ActorRegistryState) XXX_Size() int {
	return m.Size()
}
func (m *ActorRegistryState) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorRegistryState.DiscardUnknown(m)
}

var xxx_messageInfo_ActorRegistryState proto.InternalMessageInfo

func (m *ActorRegistryState) GetActors() []ActorRecord {
	if m != nil {
		return m.Actors
	}
	return nil
}

func (m *ActorRegistryState) GetCodeStore() []CodeRecord {
	if m != nil {
		return m.CodeStore
	}
	return nil
}

func (m *ActorRegistryState) GetMigrations() []ActorMigrationRecord {
	if m != nil {
		return m.Migrations
	}
	return nil
}

type CodeRecord struct {
	CodeHash     string `protobuf:"bytes,1,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	RegisteredBy string `protobuf:"bytes,2,opt,name=registered_by,json=registeredBy,proto3" json:"registered_by,omitempty"`
	RegisteredAt uint64 `protobuf:"varint,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
}

func (m *CodeRecord) Reset()         { *m = CodeRecord{} }
func (m *CodeRecord) String() string { return proto.CompactTextString(m) }
func (*CodeRecord) ProtoMessage()    {}
func (*CodeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b1bb8f3b48f62, []int{3}
}
func (m *CodeRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CodeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CodeRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CodeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeRecord.Merge(m, src)
}
func (m *CodeRecord) XXX_Size() int {
	return m.Size()
}
func (m *CodeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CodeRecord proto.InternalMessageInfo

func (m *CodeRecord) GetCodeHash() string {
	if m != nil {
		return m.CodeHash
	}
	return ""
}

func (m *CodeRecord) GetRegisteredBy() string {
	if m != nil {
		return m.RegisteredBy
	}
	return ""
}

func (m *CodeRecord) GetRegisteredAt() uint64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

type ActorRecord struct {
	ActorId          string   `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ContractAddress  string   `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Owner            string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	CodeHash         string   `protobuf:"bytes,4,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	StorageRoot      string   `protobuf:"bytes,5,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	MailboxRoot      string   `protobuf:"bytes,6,opt,name=mailbox_root,json=mailboxRoot,proto3" json:"mailbox_root,omitempty"`
	Balance          uint64   `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	LogicalTime      uint64   `protobuf:"varint,8,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	Status           string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	RentStatus       string   `protobuf:"bytes,10,opt,name=rent_status,json=rentStatus,proto3" json:"rent_status,omitempty"`
	LastActiveHeight uint64   `protobuf:"varint,11,opt,name=last_active_height,json=lastActiveHeight,proto3" json:"last_active_height,omitempty"`
	Capabilities     []string `protobuf:"bytes,12,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	MigratedFrom     string   `protobuf:"bytes,13,opt,name=migrated_from,json=migratedFrom,proto3" json:"migrated_from,omitempty"`
	MigratedTo       string   `protobuf:"bytes,14,opt,name=migrated_to,json=migratedTo,proto3" json:"migrated_to,omitempty"`
}

func (m *ActorRecord) Reset()         { *m = ActorRecord{} }
func (m *ActorRecord) String() string { return proto.CompactTextString(m) }
func (*ActorRecord) ProtoMessage()    {}
func (*ActorRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b1bb8f3b48f62, []int{4}
}
func (m *ActorRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActorRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActorRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActorRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorRecord.Merge(m, src)
}
func (m *ActorRecord) XXX_Size() int {
	return m.Size()
}
func (m *ActorRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ActorRecord proto.InternalMessageInfo

func (m *ActorRecord) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *ActorRecord) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *ActorRecord) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ActorRecord) GetCodeHash() string {
	if m != nil {
		return m.CodeHash
	}
	return ""
}

func (m *ActorRecord) GetStorageRoot() string {
	if m != nil {
		return m.StorageRoot
	}
	return ""
}

func (m *ActorRecord) GetMailboxRoot() string {
	if m != nil {
		return m.MailboxRoot
	}
	return ""
}

func (m *ActorRecord) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ActorRecord) GetLogicalTime() uint64 {
	if m != nil {
		return m.LogicalTime
	}
	return 0
}

func (m *ActorRecord) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ActorRecord) GetRentStatus() string {
	if m != nil {
		return m.RentStatus
	}
	return ""
}

func (m *ActorRecord) GetLastActiveHeight() uint64 {
	if m != nil {
		return m.LastActiveHeight
	}
	return 0
}

func (m *ActorRecord) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *ActorRecord) GetMigratedFrom() string {
	if m != nil {
		return m.MigratedFrom
	}
	return ""
}

func (m *ActorRecord) GetMigratedTo() string {
	if m != nil {
		return m.MigratedTo
	}
	return ""
}

type ActorMigrationRecord struct {
	ActorId      string `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	FromCodeHash string `protobuf:"bytes,2,opt,name=from_code_hash,json=fromCodeHash,proto3" json:"from_code_hash,omitempty"`
	ToCodeHash   string `protobuf:"bytes,3,opt,name=to_code_hash,json=toCodeHash,proto3" json:"to_code_hash,omitempty"`
	Height       uint64 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	LogicalTime  uint64 `protobuf:"varint,5,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
}

func (m *ActorMigrationRecord) Reset()         { *m = ActorMigrationRecord{} }
func (m *ActorMigrationRecord) String() string { return proto.CompactTextString(m) }
func (*ActorMigrationRecord) ProtoMessage()    {}
func (*ActorMigrationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b1bb8f3b48f62, []int{5}
}
func (m *ActorMigrationRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActorMigrationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActorMigrationRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActorMigrationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorMigrationRecord.Merge(m, src)
}
func (m *ActorMigrationRecord) XXX_Size() int {
	return m.Size()
}
func (m *ActorMigrationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorMigrationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ActorMigrationRecord proto.InternalMessageInfo

func (m *ActorMigrationRecord) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *ActorMigrationRecord) GetFromCodeHash() string {
	if m != nil {
		return m.FromCodeHash
	}
	return ""
}

func (m *ActorMigrationRecord) GetToCodeHash() string {
	if m != nil {
		return m.ToCodeHash
	}
	return ""
}

func (m *ActorMigrationRecord) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ActorMigrationRecord) GetLogicalTime() uint64 {
	if m != nil {
		return m.LogicalTime
	}
	return 0
}

type GenesisState struct {
	Version        uint64              `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Params         Params              `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
	RegistryParams ActorRegistryParams `protobuf:"bytes,3,opt,name=registry_params,json=registryParams,proto3" json:"registry_params"`
	State          ActorRegistryState  `protobuf:"bytes,4,opt,name=state,proto3" json:"state"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b1bb8f3b48f62, []int{6}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetRegistryParams() ActorRegistryParams {
	if m != nil {
		return m.RegistryParams
	}
	return ActorRegistryParams{}
}

func (m *GenesisState) GetState() ActorRegistryState {
	if m != nil {
		return m.State
	}
	return ActorRegistryState{}
}

func init() {
	proto.RegisterType((*Params)(nil), "l1.actorregistry.v1.Params")
	proto.RegisterType((*ActorRegistryParams)(nil), "l1.actorregistry.v1.ActorRegistryParams")
	proto.RegisterType((*ActorRegistryState)(nil), "l1.actorregistry.v1.ActorRegistryState")
	proto.RegisterType((*CodeRecord)(nil), "l1.actorregistry.v1.CodeRecord")
	proto.RegisterType((*ActorRecord)(nil), "l1.actorregistry.v1.ActorRecord")
	proto.RegisterType((*ActorMigrationRecord)(nil), "l1.actorregistry.v1.ActorMigrationRecord")
	proto.RegisterType((*GenesisState)(nil), "l1.actorregistry.v1.GenesisState")
}

func init() { proto.RegisterFile("l1/actorregistry/v1/genesis.proto", fileDescriptor_570b1bb8f3b48f62) }

var fileDescriptor_570b1bb8f3b48f62 = []byte{
	// 947 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xce, 0xc6, 0x8e, 0x13, 0x1f, 0xdb, 0x49, 0x99, 0xb8, 0x61, 0xa1, 0xe0, 0xb8, 0x06, 0x51,
	0x57, 0x02, 0x1b, 0x07, 0x04, 0x42, 0x48, 0x48, 0x49, 0x2a, 0x5a, 0x24, 0x10, 0x61, 0x53, 0x15,
	0x09, 0x21, 0xad, 0xc6, 0xbb, 0x27, 0xeb, 0x91, 0x76, 0x77, 0xcc, 0xcc, 0xd8, 0x8d, 0xef, 0xe0,
	0x0d, 0x78, 0x18, 0x1e, 0xa2, 0x97, 0xbd, 0x44, 0x5c, 0x20, 0x94, 0x5c, 0xf2, 0x04, 0xdc, 0xa1,
	0xf9, 0xd9, 0xd8, 0xdb, 0x9a, 0x72, 0x65, 0xcf, 0xf7, 0x7d, 0xe7, 0x9c, 0x99, 0xf3, 0x9d, 0x99,
	0x85, 0xbb, 0xe9, 0x68, 0x48, 0x23, 0xc5, 0x85, 0xc0, 0x84, 0x49, 0x25, 0x16, 0xc3, 0xf9, 0x68,
	0x98, 0x60, 0x8e, 0x92, 0xc9, 0xc1, 0x54, 0x70, 0xc5, 0xc9, 0x7e, 0x3a, 0x1a, 0x94, 0x24, 0x83,
	0xf9, 0xe8, 0xcd, 0x76, 0xc2, 0x13, 0x6e, 0xf8, 0xa1, 0xfe, 0x67, 0xa5, 0xbd, 0x7f, 0x3c, 0xa8,
	0x9d, 0x51, 0x41, 0x33, 0x49, 0x7c, 0xd8, 0xc6, 0x9c, 0x8e, 0x53, 0x8c, 0x7d, 0xaf, 0xeb, 0xf5,
	0x77, 0x82, 0x62, 0x49, 0xee, 0xc1, 0x9e, 0x42, 0xa9, 0x72, 0x54, 0xe1, 0x54, 0xf0, 0x0b, 0x96,
	0xa2, 0xbf, 0x69, 0x14, 0xbb, 0x0e, 0x3e, 0xb3, 0x28, 0xf9, 0x04, 0x5e, 0x9f, 0x0a, 0x1e, 0xcf,
	0x22, 0xc5, 0x78, 0x1e, 0xce, 0x51, 0x48, 0xfd, 0x9b, 0x50, 0x85, 0x7e, 0xa5, 0xeb, 0xf5, 0xeb,
	0xc1, 0xed, 0x25, 0xfd, 0xc4, 0xb2, 0x0f, 0xa9, 0x42, 0xf2, 0x16, 0xd4, 0xe9, 0x4c, 0x4d, 0xb8,
	0x60, 0x6a, 0xe1, 0x57, 0x8d, 0x72, 0x09, 0x90, 0x01, 0xec, 0xc7, 0x78, 0x41, 0x67, 0xa9, 0x0a,
	0x7f, 0x9a, 0xa1, 0x58, 0x84, 0x29, 0xcb, 0x98, 0xf2, 0xb7, 0xba, 0x5e, 0xbf, 0x1a, 0xbc, 0xe6,
	0xa8, 0xef, 0x34, 0xf3, 0xb5, 0x26, 0xc8, 0x7b, 0xb0, 0x97, 0xd1, 0xcb, 0x92, 0xb6, 0x66, 0xb4,
	0xad, 0x8c, 0x5e, 0x2e, 0x75, 0xbd, 0x9f, 0x37, 0x61, 0xff, 0x58, 0xb7, 0x29, 0x70, 0x6d, 0x72,
	0x8d, 0x78, 0x1b, 0x40, 0xc7, 0x9b, 0x0e, 0x4a, 0xd3, 0x8b, 0x56, 0x50, 0xcf, 0xe8, 0xa5, 0xd1,
	0x4a, 0x72, 0x1f, 0x6e, 0x69, 0x3a, 0xa2, 0x53, 0x3a, 0x66, 0x29, 0x53, 0x0c, 0xa5, 0x69, 0x47,
	0x2b, 0xd0, 0x65, 0x4f, 0x57, 0x60, 0xf2, 0x21, 0xb4, 0x63, 0x4c, 0x51, 0x61, 0x1c, 0xce, 0x69,
	0x3a, 0xc3, 0x70, 0xca, 0x53, 0x16, 0x2d, 0x5c, 0x33, 0x88, 0xe3, 0x9e, 0x68, 0xea, 0xcc, 0x30,
	0xe4, 0x63, 0x38, 0x28, 0x47, 0x08, 0x8c, 0x99, 0xc0, 0x48, 0xb9, 0xb6, 0xb4, 0x57, 0x63, 0x02,
	0xc7, 0x91, 0x4f, 0xc1, 0xa7, 0x69, 0xca, 0x9f, 0x86, 0xe5, 0x58, 0x89, 0x79, 0x6c, 0xda, 0xb4,
	0x13, 0xdc, 0x36, 0xfc, 0x83, 0x95, 0xe0, 0x73, 0xcc, 0xe3, 0xde, 0xdf, 0x1e, 0x90, 0x52, 0x0b,
	0xce, 0x95, 0xf6, 0xe3, 0x0b, 0xa8, 0xdd, 0x9c, 0xbe, 0xd2, 0x6f, 0x1c, 0x75, 0x07, 0x6b, 0x26,
	0x6a, 0xe0, 0x02, 0x23, 0x2e, 0xe2, 0x93, 0xea, 0xb3, 0x3f, 0x0f, 0x37, 0x02, 0x17, 0x45, 0x1e,
	0x00, 0x44, 0x3c, 0xc6, 0x50, 0x2a, 0x2e, 0xf4, 0xac, 0xe8, 0x1c, 0x87, 0x6b, 0x73, 0x9c, 0xf2,
	0x18, 0x4b, 0x29, 0xea, 0x3a, 0xf0, 0x5c, 0xc7, 0x91, 0x6f, 0x01, 0x32, 0x96, 0x08, 0xaa, 0xa7,
	0x45, 0xfa, 0x15, 0x93, 0xe5, 0xfe, 0x7f, 0xef, 0xe4, 0x9b, 0x42, 0x5b, 0xca, 0xb7, 0x92, 0xa2,
	0x27, 0x01, 0x96, 0xf5, 0xc8, 0x1d, 0x30, 0xb5, 0xc2, 0x09, 0x95, 0x13, 0xe3, 0x72, 0x3d, 0xd8,
	0xd1, 0xc0, 0x23, 0x2a, 0x27, 0xe4, 0x1d, 0x68, 0xd9, 0x02, 0x28, 0x30, 0x0e, 0xc7, 0x0b, 0xe3,
	0x70, 0x3d, 0x68, 0x2e, 0xc1, 0x93, 0xc5, 0x0b, 0x22, 0xaa, 0x8c, 0xaf, 0xd5, 0x55, 0xd1, 0xb1,
	0xea, 0xfd, 0x51, 0x81, 0xc6, 0x4a, 0xa7, 0xc8, 0x1b, 0xb0, 0x63, 0xf6, 0x1f, 0xb2, 0xd8, 0x55,
	0xdd, 0x36, 0xeb, 0xaf, 0x62, 0x3d, 0x59, 0x11, 0xcf, 0x95, 0xa0, 0x91, 0x0a, 0x69, 0x1c, 0x0b,
	0x94, 0xd2, 0xd5, 0xdd, 0x2b, 0xf0, 0x63, 0x0b, 0x93, 0x36, 0x6c, 0xf1, 0xa7, 0x39, 0x0a, 0x37,
	0x4a, 0x76, 0x51, 0x3e, 0x52, 0xf5, 0x85, 0x23, 0xdd, 0x85, 0xa6, 0xf6, 0x83, 0x26, 0x18, 0x0a,
	0xce, 0xed, 0xfd, 0xa9, 0x07, 0x0d, 0x87, 0x05, 0x9c, 0x2b, 0x2d, 0xc9, 0x28, 0x4b, 0xc7, 0xfc,
	0xd2, 0x4a, 0x6a, 0x56, 0xe2, 0x30, 0x23, 0xf1, 0x61, 0x7b, 0x4c, 0x53, 0x9a, 0x47, 0xe8, 0x6f,
	0x9b, 0xd3, 0x16, 0x4b, 0x1d, 0x9c, 0xf2, 0x84, 0x45, 0x34, 0x0d, 0x15, 0xcb, 0xd0, 0xdf, 0x31,
	0x74, 0xc3, 0x61, 0x8f, 0x59, 0x86, 0xe4, 0x00, 0x6a, 0x52, 0x51, 0x35, 0x93, 0x7e, 0xdd, 0x64,
	0x76, 0x2b, 0x72, 0x08, 0x0d, 0x81, 0xb9, 0x0a, 0x1d, 0x09, 0x86, 0x04, 0x0d, 0x9d, 0x5b, 0xc1,
	0xfb, 0x40, 0x52, 0x2a, 0x95, 0xbe, 0x93, 0x6c, 0x8e, 0xe1, 0x04, 0x59, 0x32, 0x51, 0x7e, 0xc3,
	0x54, 0xb8, 0xa5, 0x99, 0x63, 0x43, 0x3c, 0x32, 0x38, 0xe9, 0x41, 0xb3, 0x74, 0x3b, 0x9b, 0xdd,
	0x8a, 0xf6, 0x6e, 0x15, 0xd3, 0xde, 0xd9, 0xc9, 0xc0, 0x38, 0xbc, 0x10, 0x3c, 0xf3, 0x5b, 0xd6,
	0xe0, 0x02, 0xfc, 0x52, 0xf0, 0x4c, 0xef, 0xeb, 0x46, 0xa4, 0xb8, 0xbf, 0x6b, 0xf7, 0x55, 0x40,
	0x8f, 0x79, 0xef, 0x37, 0x0f, 0xda, 0xeb, 0x86, 0xef, 0x55, 0x2e, 0xbf, 0x0b, 0xbb, 0xba, 0x60,
	0xb8, 0x74, 0xca, 0xcd, 0x96, 0x46, 0x4f, 0x0b, 0xb7, 0xba, 0xd0, 0x54, 0x7c, 0x45, 0x63, 0x7d,
	0x06, 0xc5, 0x6f, 0x14, 0x07, 0x50, 0x73, 0x7d, 0xa8, 0x9a, 0x3e, 0xb8, 0xd5, 0x4b, 0x3e, 0x6c,
	0xbd, 0xe4, 0x43, 0xef, 0x97, 0x4d, 0x68, 0x3e, 0xb4, 0x9f, 0x0c, 0x7b, 0xe1, 0x7d, 0xd8, 0x76,
	0xaf, 0xb5, 0xd9, 0x6d, 0x35, 0x28, 0x96, 0xe4, 0x33, 0xa8, 0x4d, 0xcd, 0xb3, 0x68, 0x76, 0xd9,
	0x38, 0xba, 0xb3, 0xf6, 0x02, 0xda, 0x97, 0xb3, 0x78, 0x05, 0x6c, 0x00, 0xf9, 0x1e, 0xf6, 0x0a,
	0x4d, 0xe8, 0x72, 0x54, 0x4c, 0x8e, 0xfe, 0xab, 0x9e, 0x93, 0xd5, 0xa7, 0xd8, 0x25, 0xdc, 0x15,
	0xe5, 0x07, 0xfa, 0x14, 0xb6, 0xf4, 0xa4, 0xa0, 0x39, 0x78, 0xe3, 0xe8, 0xde, 0xff, 0xa7, 0x33,
	0xa7, 0x74, 0xd9, 0x6c, 0xec, 0xc9, 0x8f, 0xcf, 0xae, 0x3a, 0xde, 0xf3, 0xab, 0x8e, 0xf7, 0xd7,
	0x55, 0xc7, 0xfb, 0xf5, 0xba, 0xb3, 0xf1, 0xfc, 0xba, 0xb3, 0xf1, 0xfb, 0x75, 0x67, 0xe3, 0x87,
	0x93, 0x84, 0xa9, 0xc9, 0x6c, 0x3c, 0x88, 0x78, 0x36, 0x94, 0x7c, 0x8e, 0x02, 0x59, 0x92, 0x7f,
	0x90, 0x8e, 0x86, 0xfa, 0xcb, 0x3b, 0x65, 0xc3, 0x35, 0x1f, 0xe0, 0xcf, 0x4b, 0xc0, 0x7c, 0x34,
	0xae, 0x99, 0xcf, 0xeb, 0x47, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xda, 0x23, 0x25, 0x25, 0xae,
	0x07, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxQueryLimit != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxQueryLimit))
		i--
		dAtA[i] = 0x30
	}
	if m.DefaultQueryLimit != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DefaultQueryLimit))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ProductionVersionGate) > 0 {
		i -= len(m.ProductionVersionGate)
		copy(dAtA[i:], m.ProductionVersionGate)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ProductionVersionGate)))
		i--
		dAtA[i] = 0x1a
	}
	if m.TestnetProfile {
		i--
		if m.TestnetProfile {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ActorRegistryParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActorRegistryParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActorRegistryParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AllowDeletedValueSend {
		i--
		if m.AllowDeletedValueSend {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.DeletedValueRedirect) > 0 {
		i -= len(m.DeletedValueRedirect)
		copy(dAtA[i:], m.DeletedValueRedirect)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.DeletedValueRedirect)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DeletedValuePolicy) > 0 {
		i -= len(m.DeletedValuePolicy)
		copy(dAtA[i:], m.DeletedValuePolicy)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.DeletedValuePolicy)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MaxCapabilities != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxCapabilities))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxActors != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxActors))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ActorRegistryState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActorRegistryState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActorRegistryState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Migrations) > 0 {
		for iNdEx := len(m.Migrations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Migrations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.CodeStore) > 0 {
		for iNdEx := len(m.CodeStore) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CodeStore[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Actors) > 0 {
		for iNdEx := len(m.Actors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Actors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CodeRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CodeRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CodeRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RegisteredAt != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RegisteredAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RegisteredBy) > 0 {
		i -= len(m.RegisteredBy)
		copy(dAtA[i:], m.RegisteredBy)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.RegisteredBy)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CodeHash) > 0 {
		i -= len(m.CodeHash)
		copy(dAtA[i:], m.CodeHash)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.CodeHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActorRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActorRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActorRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MigratedTo) > 0 {
		i -= len(m.MigratedTo)
		copy(dAtA[i:], m.MigratedTo)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MigratedTo)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.MigratedFrom) > 0 {
		i -= len(m.MigratedFrom)
		copy(dAtA[i:], m.MigratedFrom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MigratedFrom)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Capabilities) > 0 {
		for iNdEx := len(m.Capabilities) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Capabilities[iNdEx])
			copy(dAtA[i:], m.Capabilities[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Capabilities[iNdEx])))
			i--
			dAtA[i] = 0x62
		}
	}
	if m.LastActiveHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastActiveHeight))
		i--
		dAtA[i] = 0x58
	}
	if len(m.RentStatus) > 0 {
		i -= len(m.RentStatus)
		copy(dAtA[i:], m.RentStatus)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.RentStatus)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x4a
	}
	if m.LogicalTime != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LogicalTime))
		i--
		dAtA[i] = 0x40
	}
	if m.Balance != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Balance))
		i--
		dAtA[i] = 0x38
	}
	if len(m.MailboxRoot) > 0 {
		i -= len(m.MailboxRoot)
		copy(dAtA[i:], m.MailboxRoot)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MailboxRoot)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.StorageRoot) > 0 {
		i -= len(m.StorageRoot)
		copy(dAtA[i:], m.StorageRoot)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.StorageRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CodeHash) > 0 {
		i -= len(m.CodeHash)
		copy(dAtA[i:], m.CodeHash)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.CodeHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ActorId) > 0 {
		i -= len(m.ActorId)
		copy(dAtA[i:], m.ActorId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ActorId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActorMigrationRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActorMigrationRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActorMigrationRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LogicalTime != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LogicalTime))
		i--
		dAtA[i] = 0x28
	}
	if m.Height != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ToCodeHash) > 0 {
		i -= len(m.ToCodeHash)
		copy(dAtA[i:], m.ToCodeHash)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ToCodeHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FromCodeHash) > 0 {
		i -= len(m.FromCodeHash)
		copy(dAtA[i:], m.FromCodeHash)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.FromCodeHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ActorId) > 0 {
		i -= len(m.ActorId)
		copy(dAtA[i:], m.ActorId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ActorId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.RegistryParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Version != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	if m.TestnetProfile {
		n += 2
	}
	l = len(m.ProductionVersionGate)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.DefaultQueryLimit != 0 {
		n += 1 + sovGenesis(uint64(m.DefaultQueryLimit))
	}
	if m.MaxQueryLimit != 0 {
		n += 1 + sovGenesis(uint64(m.MaxQueryLimit))
	}
	return n
}

func (m *ActorRegistryParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxActors != 0 {
		n += 1 + sovGenesis(uint64(m.MaxActors))
	}
	if m.MaxCapabilities != 0 {
		n += 1 + sovGenesis(uint64(m.MaxCapabilities))
	}
	l = len(m.DeletedValuePolicy)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.DeletedValueRedirect)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.AllowDeletedValueSend {
		n += 2
	}
	return n
}

func (m *ActorRegistryState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Actors) > 0 {
		for _, e := range m.Actors {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CodeStore) > 0 {
		for _, e := range m.CodeStore {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Migrations) > 0 {
		for _, e := range m.Migrations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *CodeRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CodeHash)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.RegisteredBy)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.RegisteredAt != 0 {
		n += 1 + sovGenesis(uint64(m.RegisteredAt))
	}
	return n
}

func (m *ActorRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ActorId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.CodeHash)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.StorageRoot)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.MailboxRoot)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Balance != 0 {
		n += 1 + sovGenesis(uint64(m.Balance))
	}
	if m.LogicalTime != 0 {
		n += 1 + sovGenesis(uint64(m.LogicalTime))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.RentStatus)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.LastActiveHeight != 0 {
		n += 1 + sovGenesis(uint64(m.LastActiveHeight))
	}
	if len(m.Capabilities) > 0 {
		for _, s := range m.Capabilities {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = len(m.MigratedFrom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.MigratedTo)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *ActorMigrationRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ActorId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.FromCodeHash)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ToCodeHash)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovGenesis(uint64(m.Height))
	}
	if m.LogicalTime != 0 {
		n += 1 + sovGenesis(uint64(m.LogicalTime))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovGenesis(uint64(m.Version))
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.RegistryParams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.State.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestnetProfile", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TestnetProfile = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductionVersionGate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductionVersionGate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultQueryLimit", wireType)
			}
			m.DefaultQueryLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultQueryLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxQueryLimit", wireType)
			}
			m.MaxQueryLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxQueryLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActorRegistryParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActorRegistryParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActorRegistryParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxActors", wireType)
			}
			m.MaxActors = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxActors |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCapabilities", wireType)
			}
			m.MaxCapabilities = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCapabilities |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedValuePolicy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeletedValuePolicy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedValueRedirect", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeletedValueRedirect = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowDeletedValueSend", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowDeletedValueSend = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActorRegistryState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActorRegistryState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActorRegistryState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Actors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Actors = append(m.Actors, ActorRecord{})
			if err := m.Actors[len(m.Actors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeStore", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeStore = append(m.CodeStore, CodeRecord{})
			if err := m.CodeStore[len(m.CodeStore)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Migrations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Migrations = append(m.Migrations, ActorMigrationRecord{})
			if err := m.Migrations[len(m.Migrations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CodeRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CodeRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CodeRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegisteredBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			m.RegisteredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActorRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActorRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActorRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StorageRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MailboxRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MailboxRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			m.Balance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Balance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogicalTime", wireType)
			}
			m.LogicalTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogicalTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RentStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RentStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastActiveHeight", wireType)
			}
			m.LastActiveHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastActiveHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capabilities", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Capabilities = append(m.Capabilities, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigratedFrom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MigratedFrom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigratedTo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MigratedTo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActorMigrationRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActorMigrationRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActorMigrationRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromCodeHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromCodeHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToCodeHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToCodeHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogicalTime", wireType)
			}
			m.LogicalTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogicalTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RegistryParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
